### ISSUE TITLE
"getJS" method in headerScript doesn't work

### ISSUE THREAD

**Issue by mj-kiwi** [axis/axiscommerce#1]
I try to make a template for axis, but when I use the "getJS" method, there's an error shows as below:

Fatal error: Call to a member function getJS() on a non-object 

can you show me the example to use this method, thanks!

**Comment by vovayatsyuk** [comment]
Just write 
$this->headScript()->appendFile('myjs.js') 
in your *.phtml file.

Don't forget to put the myjs.js to your template skin/js folder.

**Comment by mj-kiwi** [comment]
it work! thanks a lot
