### ISSUE TITLE
[question] Отображение картинки производителя в карточке товара

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#10]
В карточке товара выводиться только **manufacturer_id** (просмотрел весь массив **Zend_Registry** и **$this** выводимые в файле _\app\design\front\default\templates\catalog\index\product.phtml_). Необходимо также выводить Name / Url / Image / Title (русский) которые представлены в _admin/catalog_manufacturer_.

Если вы считаете что это не нужно выводить подскажите, пожалуйста, в каком файле прописать дополнительный запрос к таблице с производителями.

**Comment by vovayatsyuk** [comment]
Данные производителя добавлены в $this->product['manufacturer']. Если производителя у товара нет, там будет null.
