### ISSUE TITLE
Реализация дополнительной сортировки в поиске

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#11]
Необходимо в поиске реализовать сортировку результатов по Цене, Брендам, новинкам, рекомендуемым, специальной цене и по различным дополнительным свойствам товара (которые указаны в карточке выводимого товара, вкладка properties). Но в выдаваемом массиве **$this->results** файла _\app\design\front\default\templates\search\index\result\product.phtml_ не достаточно данных для реализации желаемого функционала. 
Подскажите в каком файле прописывать дополнительные запросы к БД чтобы в массив были выведены нужные данные?

P.S. по какому принципу сейчас выводятся результаты? релевантность (полнота запроса), дата или?

**Comment by vovayatsyuk** [comment]
Данные отображаются в порядке релевантности. Релевантность определяется классом Zend_Search_Lucene_Search_Similarity.

Сейчас у нас нет механизмов влияния на сортировку результатов.

**Comment by brokerUA** [comment]
Нашел как добавить в соответствующий массив необходимые мне данные, а влиять на сортировку будем обходом массива циклом foreach.

К примеру сейчас в массиве **$this->results** нет значения **sku**. Для его добавления редактируем _scripts/searchIndexMaker.php_
    118  $product['image_title'],
    119  $product['sku']

```
175  function createDoc($type, $name, $content, $url, $imagePath = null, $imageTitle = null, $sku)

198  $doc->addField(Zend_Search_Lucene_Field::UnIndexed(
199          'sku', $sku, 'utf-8'
200  ));
```

Далее в файле _\app\code\Axis\Search\Model\Lucene.php_ добавляем
    174  'sku' =>  $doc->sku,
Заходим в админку и обновляем поисковый индекс.
Теперь в поиске в массиве **$this->results** присутствует значения **sku** найденного товара.

Таким же способом, редактируя запрос (92 строка) в файле _scripts/searchIndexMaker.php_ можно вывести необходимую информацию в результаты поиска.

**Comment by 0m3r** [comment]
закриваю тогда
