### ISSUE TITLE
Перевод админки после последних правок

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#12]
После внесения последних коммитов, в админке главное меню, статистика и приветствие вверху, а также Interface locale: при переключении языков интерфейса всегда на английском.

**Comment by 0m3r** [comment]
Наподобие описаному здесь
http://github.com/axis/axiscommerce/issues#issue/9/comment/483070

**Comment by brokerUA** [comment]
Поясните, пожалуйста, что имели ввиду ссылаясь на #9.
У меня установлены все правки, в том числе #9, язык в конфиге выставлен как русский для backend и frontend

**Comment by 0m3r** [comment]
бага возникла как следствие фикса на #9.
Времено можете решить у себя так : в Axis.php заменить
if (null === self::$_translator) {
...
}
на return Axis_Translate::getInstance($name);

**Comment by brokerUA** [comment]
Спасибо, временно поправил...

**Comment by 0m3r** [comment]
закриваю
