### ISSUE TITLE
public_html/axis/app/code/Axis/Catalog/Model/Product/Row.php on line 136

### ISSUE THREAD

**Issue by lehmandodoe** [axis/axiscommerce#128]
when I place a new product in the product catalog menu, it show an error :

" public_html/axis/app/code/Axis/Catalog/Model/Product/Row.php on line 136 "

we just install the Axis store

**Comment by vovayatsyuk** [comment]
Can you include the error message also?

If the error is telling about the error with array - check the magic_quotes directive. It should be disabled to work with Axis.

**Comment by lehmandodoe** [comment]
hello there,
just everytime I add a product, it shows this error and none of the products were added (back-end nor front-end)
it is all the error message shown about and i cannot find myself the way out :)

Kind Regards,L.Dodoe

--- On Fri, 2/3/12, Vova Yatsyuk reply@reply.github.com wrote:

**Comment by vovayatsyuk** [comment]
Do the following:
- Open app/code/Axis/Catalog/Model/Product/Row.php and go to the line 136
- Add code:
  
  Axis::message()->addError(Zend_Debug::dump($data, null, false));return $this;
- Save the file and try to add another product with image
- An error message will appear. Please attach it to this thread.

**Comment by lehmandodoe** [comment]
Attached is my server requirement problem
is it setting from the script-side or from the cPanel/hosting server side ?
Particularly, I have installed Axis from the cPanel and I find this problemafter adding the line with this per your advise, it shows other error message :

Notice: Undefined index: 2 in /home/sa-store/app/code/Axis/Discount/Model/Discount.php on line 264

--- On Wed, 2/8/12, Vova Yatsyuk reply@reply.github.com wrote:

**Comment by vovayatsyuk** [comment]
Looks like this is another problem. I have fix it in the repository some time ago.

You can save the product without this error, if you will set at least one category assignment before save. You can also replace the file app/code/Axis/Discount/Model/Discount.php with the new one from repo: https://raw.github.com/axis/axiscommerce/develop/app/code/Axis/Discount/Model/Discount.php

**Comment by lehmandodoe** [comment]
Hi Vova,

FYI, i just download the script from axiscommerce.com and experienced the trouble, and it is fixed nowthanks for your valued time and the great job!

--- On Fri, 2/10/12, Vova Yatsyuk reply@reply.github.com wrote:
