### ISSUE TITLE
При "Оформить заказ/Перейти к оплате" Ошибка HTTP 500

### ISSUE THREAD

**Issue by salavat** [axis/axiscommerce#129]
Ошибка HTTP 500 (Internal Server Error): При попытке сервера выполнить запрос возникла неожиданная ситуация.

**Comment by vovayatsyuk** [comment]
Обсуждение на форуме: http://axiscommerce.com/forum/%D0%BF%D1%80%D0%B8-%D0%BE%D1%84%D0%BE%D1%80%D0%BC%D0%B8%D1%82%D1%8C-%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%BF%D0%B5%D1%80%D0%B5%D0%B9%D1%82%D0%B8-%D0%BA-%D0%BE%D0%BF%D0%BB%D0%B0%D1%82%D0%B5-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-http-500
