### ISSUE TITLE
Вопрос по prperties и variation массива в спсике товаров

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#13]
Просматриваю массив **$this->products** 
в файле _\app\design\front\default\templates\catalog\box\new.phtml_
1. Там выводятся данные variation которые в карточке товара не указаны вообще, причем выводиться в каждом товаре.
       [variation] =&gt; Array
           (
               [0] =&gt; Array
                   (
                       [id] =&gt; 0
                       [price_amount] =&gt; 0.0000
                       [price_type] =&gt; by
                       [sku] =&gt; 1286681
                       [quantity] =&gt; 10.0000
                       [weight_amount] =&gt; 0.00
                       [weight_type] =&gt; by
                   )
           )
2. В том же массиве того же файла не выводятся prperties, их как раз в карточке товара указано аж 3 шт.
   Это ошибка или так задумано? необходимо получить заначения prperties в указанном массиве, т.к. (по крайней мере в моем случае) они выводят всевозможные стикеры (лимитед едишен, только онлайн и пр.) для конкретного товара.

P.S. В самой карточке товара выводиться все правильно.

**Comment by 0m3r** [comment]
эти данные там конечно избыточны но с-другой стороны могут кому нибудь сгодитса.
c proporties ет Вы дельно заметили пропустили мы, добавлю  скорее всего 
p.s. млин нажал comment && close нечаянно
