### ISSUE TITLE
XSS в админке

### ISSUE THREAD

**Issue by maxnag** [axis/axiscommerce#130]
Админка - пользователи - изменить существующего.
Просто в фамилию добавил (конкатенировал) <script>alert('1')</script> и сохранил, после этого увы ошибка JS

invalid regular expression flag s

alert('1')</sc </span>&nbsp;|&nbsp;

user (line 78, col 17)

Версия 0,8,6

**Comment by vovayatsyuk** [comment]
Не могу повторить: http://demo.axiscommerce.com/admin/account/customer/index/customerId/32

Уже изменил фамилию на 

```
asdd <script>alert('1')</script>
```

Вроде все работает.
