### ISSUE TITLE
Не изменяется название категории в каталоге продуктов

### ISSUE THREAD

**Issue by kot761** [axis/axiscommerce#131]
При попытке изменить название категории в каталоге продуктов выскакивает сообщение "Category not exist", название категории не меняется

**Comment by vovayatsyuk** [comment]
Странно. Такая ошибка должна появляться при открытии окна категории, или после сохранения, но не перед сохранением.

Ошибка появляется на тех категориях, которые были сохранены с ошибками? Вероятно не сохранилась ссылка на категорию. И этот отчет https://github.com/axis/axiscommerce/issues/132 напрямую связан с этим.

Когда открываете категорию, кроме названия, еще какие-то поля не сохранились с прошлого раза?

**Comment by kot761** [comment]
Если под открытием категории имеется ввиду список товаров в ней, то он сохранен. Если же дополнительные поля, то их не вводил, но сейчас проверю.
Сама категория не открывается для редактирования. И у меня все категории сохранены с той ошибкой, поэтому отредактировать не могу ни одну. Удаляются же категории нормально.
Что интересно - создал только что новую категорию, заполнил все поля (до этого вводил только Название), категория сохранилась, стала отображаться в меню и открывается для редактирования. А те категории что не открываются для редактирования в меню не отображаются (думал что они не отображались потому что товаров в них еще нет).
Вот, нашел - создаю подкатегорию, ввожу только название, поле ссылка пустое. Получаю ошибку и категорию которая не открывается для редактирования. Следом за ней создаю в этой же группе товаров еще одну подкатегорию, но ввожу название и ссылку - категория сохраняется и доступна для редактирования.

**Comment by vovayatsyuk** [comment]
Спасибо. Смог повторить. 

Проблема была в использовании strtolower с кирилическими буквами, что приводило к созданию пустой ссылки и дальнейшей поломки логики.

Исправлено https://github.com/axis/axiscommerce/commit/4c7c9df1f9b8e860c04dd11c73928603c2fe159d
