### ISSUE TITLE
Не могу добавить продукт

### ISSUE THREAD

**Issue by maxnag** [axis/axiscommerce#136]
При добавлении продукта, иногда нажимал "Сохранить и продолжить". Когда нажимаю сохранить выскакивает сообщение Notice: Undefined index: 3 in /var/www/Axis/app/code/Axis/Discount/Model/Discount.php on line 264 и ничего сохранить не получается, еще выскакивает Product sku must be unique value, хотя это первые продукт и СКУ и так уникальный.

**Comment by maxnag** [comment]
Точнее продукт, оказывается, добавляется, но из-за первой ошибки, не происходит закрытия окна.

**Comment by vovayatsyuk** [comment]
Ошибка проявляется если продукт не привязать к категории.

Чтобы избежать такой ошибки, отметьте категорию (в окне продукта на вкладке "Категории") перед сохранением.

**Comment by maxnag** [comment]
А как я могу добавить категорию, один из тикетов мне этого не позволяет (я убил все категории и новые не могу создать)

**Comment by vovayatsyuk** [comment]
Пока можете создать корневую категорию с помощью нового сайта. 

Я написал ответ в соответствующей теме https://github.com/axis/axiscommerce/issues/133#issuecomment-3798053
