### ISSUE TITLE
При входе в загрузку CSV ОШИБКА!!!

### ISSUE THREAD

**Issue by grevinden** [axis/axiscommerce#144]
axis_axis_csv_profile' doesn't exist

**Comment by vovayatsyuk** [comment]
Ошибка проявляется при использовании префикса таблиц. Исправлено в репозитории и будет доступно в следующей версии.

https://github.com/axis/axiscommerce/commit/d85d2e7cb2694239471f0f8d1332ddf4fd3d20e5
