### ISSUE TITLE
Ошибка в переводе админки (RU)

### ISSUE THREAD

**Issue by kehskas** [axis/axiscommerce#146]
Администрирование > Импорт/Экспорт  > Csv Импорт/Экспорт > Добавить/Редактировать любой пункт, в открывшейся форме, поле Направление: "Експорт" исправить на "Экспорт"

**Comment by vovayatsyuk** [comment]
Исправлено https://github.com/axis/axiscommerce/commit/fbefc11af9ce32169496500dc3f54076f45ca815
