### ISSUE TITLE
Free shipping

### ISSUE THREAD

**Issue by vizo** [axis/axiscommerce#149]
I selected ZONE ..my country Slovenia for free shipping standard and minimal order total 30 ... Minimal works ok.. but when i reach over 30, even from other countries can get free shipping... Is this a bug?

**Comment by vovayatsyuk** [comment]
Can't reproduce.

Check your geozone setup for the Slovenia.

What I did:
- Add geozone 'USA' on admin/location/geozone and save it.
- Add Zone for the USA on the same page. Country: United States, Zone: All
- Setted up the shipping/Free_Standard/geozone option. 
- Setted up the shipping/Free_Standard/minOrderTotal option.

**Comment by vizo** [comment]
I did exactly same for Slovenia ...

minOrderTotal works ... but for all countries :(( .. not just for Slovenia, but on geozone list i have just Slovenia ...

**Comment by vizo** [comment]
Hmmm ... i changed geozone name to "FREE SHIPPING ZONE" (before i had "Slovenia" as name too), then i cleared cache .. now suddenly works :D I did clear cache before a lot of times .. so i really don't see connection about all that.. but anyway now works :) Thanks! :)
