### ISSUE TITLE
Special Price (Discount.php)

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#15]
1) Создаю товар, указываю Special Price, Special Price From, Special Price To выдает в блоке сообщений

```
Notice: Trying to get property of non-object in D:\xampp\htdocs\___CMS_axis\app\code\Axis\Discount\Model\Discount.php on line 630
```

и сразу после него 

```
Data was saved successfully
```

и сохраняется без указания полей спеццен и без поля Name.

**php.log**
     2010-10-25T14:37:47+04:00 DEBUG (7): Notice: Trying to get property of non-object in D:\xampp\htdocs___CMS_axis\app\code\Axis\Discount\Model\Discount.php on line 630
    ##0 D:\xampp\htdocs___CMS_axis\app\code\Axis\Discount\Model\Discount.php(630): AxisErrorHandler(8, 'Trying to get p...', 'D:\xampp\htdocs...', 630, Array)
    ##1 D:\xampp\htdocs___CMS_axis\app\code\Axis\Catalog\Model\Product\Row.php(198): Axis_Discount_Model_Discount->setSpecialPrice('139', '5', '2010-10-12', '2010-10-31')
    ##2 D:\xampp\htdocs___CMS_axis\app\code\Axis\Admin\controllers\Catalog\IndexController.php(238): Axis_Catalog_Model_Product_Row->setSpecial(Array)
    ##3 D:\xampp\htdocs___CMS_axis\library\Zend\Controller\Action.php(513): Axis_Admin_Catalog_IndexController->saveProductAction()
    ##4 D:\xampp\htdocs___CMS_axis\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action->dispatch('saveProductActi...')
    ##5 D:\xampp\htdocs___CMS_axis\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
    ##6 D:\xampp\htdocs___CMS_axis\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
    ##7 D:\xampp\htdocs___CMS_axis\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
    ##8 D:\xampp\htdocs___CMS_axis\index.php(75): Zend_Application->run()
    ##9 {main}

2) Захожу в каталог нажимаю Add Product, добавляет нормально.
Если перед добавлением редактирую любой товар, то загружается карточка без отмеченных полей \* Status, \* Tax Class и пр. которые стояли по умолчанию.
Ставлю к примеру значение Status в Enabled, сохраняю, а оно подчеркивает как будто я не указал ничего.
Для добавления товара приходиться обновлять каталог по ссылке /admin/catalog_index

Помоему ошибки начались после внесения одних из последних правок, появилась проблема #12, #15.

**Comment by 0m3r** [comment]
1) не могу повторить. Оно у Вас еще актуально?
2) понятия значений  "которые стояли по умолчанию"  у нас нет , иначе я не понял что Вы хотите

**Comment by brokerUA** [comment]
Не актуально. Эти баги поправились в одном из прошлых коммитов.

**Comment by 0m3r** [comment]
закриваю
