### ISSUE TITLE
 Ошибка при добавлении нового товара без указания категории.

### ISSUE THREAD

**Issue by vladkrutov** [axis/axiscommerce#158]
Если добавлять товар не указав категорию, то возникает ошибка in /app/code/Axis/Discount/Model/Discount.php on line 264

**Comment by vovayatsyuk** [comment]
Испавлено в репозитории.

https://github.com/axis/axiscommerce/commit/0172a11ffac3f6fff5692a36da9bd5fde0c36ce0?w=0
https://github.com/axis/axiscommerce/commit/339c0ccd37a91839f3dc58a2571947b4ce7eee21
