### ISSUE TITLE
Перенос на хостинг

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#16]
Скопировал файлы и БД на хостинг, заменив данные в config.php и таблице core_site.
Запускаю сайт — белый лист. Закомментировал config.php, попадаю на установку /install/ <a href="http://s008.radikal.ru/i306/1010/dc/9d905b54129d.gif">выводит ошибки</a>.
Убрал в index.php 42 строку (. get_include_path()), сайт запустился все вроде работает кроме одного класса объявленного в шаблоне страницы
    <?php echo $this->box('catalog/subnavigation')
            ->setTemplate('catalog/box/submenu.phtml')
            ->setDisableWrapper(true)
            ->toHtml() ?>
На локалке все работает, а на хостинге выдает ошибку.
        2010-10-26T14:18:37+04:00 DEBUG (7): Class Axis_Catalog_Box_Subnavigation not found
     0 [internal function]: Axis_View_Helper_Box->box('catalog/subnavi...')
     1 /usr/local/www/sephora.ru/www/library/Zend/View/Abstract.php(342): call_user_func_array(Array, Array)
     2 /usr/local/www/sephora.ru/www/app/design/front/sephora/layouts/layout_catalog.phtml(56): Zend_View_Abstract->__call('box', Array)
     3 /usr/local/www/sephora.ru/www/app/design/front/sephora/layouts/layout_catalog.phtml(56): Zend_View->box('catalog/subnavi...')
     4 /usr/local/www/sephora.ru/www/library/Zend/View.php(108): include('/usr/local/www/...')
     5 /usr/local/www/sephora.ru/www/library/Zend/View/Abstract.php(880): Zend_View->_run('/usr/local/www/...')
     6 /usr/local/www/sephora.ru/www/library/Zend/Layout.php(796): Zend_View_Abstract->render('layout_catalog....')
     7 /usr/local/www/sephora.ru/www/library/Zend/Layout/Controller/Plugin/Layout.php(143): Zend_Layout->render()
     8 /usr/local/www/sephora.ru/www/library/Zend/Controller/Plugin/Broker.php(331): Zend_Layout_Controller_Plugin_Layout->postDispatch(Object(Zend_Controller_Request_Http))
     9 /usr/local/www/sephora.ru/www/library/Zend/Controller/Front.php(965): Zend_Controller_Plugin_Broker->postDispatch(Object(Zend_Controller_Request_Http))
     10 /usr/local/www/sephora.ru/www/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
     11 /usr/local/www/sephora.ru/www/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
     12 /usr/local/www/sephora.ru/www/index.php(75): Zend_Application->run()
     13 {main}

**Comment by 0m3r** [comment]
ошибка из за временного фикса,  следствия #9 и #12 :((
кстати обновитесь и "должно" быть щастье

**Comment by brokerUA** [comment]
Обновился, нет счастья... по прежнему ошибка из-за наличия get_include_path() и код выше указанного класса не работает и все это только на хостинге (на локалке работает).
P.S. баги #9 и #12 обезврежены :)

**Comment by 0m3r** [comment]
Насколько я знаю и вижу - такого бокса (Axis_Catalog_Box_Subnavigation) у нас нет, это уже ваша поделка :) и я так подозреваю что Вы не создали клас бокса, создайте его по примеру скажем Axis_Catalog_Box_Navigation.

**Comment by brokerUA** [comment]
Дело в том что на локалхосте работает, класс создан на основе Axis_Catalog_Box_Navigation.
Какие данные необходимо предоставить для решения проблемы?

**Comment by 0m3r** [comment]
ну нет у Вас там класа Axis_Catalog_Box_Subnavigation. может файл не втом регистре или  прав нету на чтение не знаю ет уже на месте смотрите.
собствено и место где смотреть Axis_View_Helper_Box line 61

```
    if (@!class_exists($boxClass)) {
        $response = Zend_Controller_Front::getInstance()->getResponse();
        if (!count($response->getException())) {
            $exception = new Axis_Exception(
                Axis::translate('core')->__(
                    'Class %s not found', $boxClass
                )
            );
```

**Comment by brokerUA** [comment]
Спасибо за подсказку действительно файл был указан не в том регистре...
(локалхост = win, хостинг = unix)
