### ISSUE TITLE
Wrong paths

### ISSUE THREAD

**Issue by vladkrutov** [axis/axiscommerce#161]
Installation failed and digging through forum showed that path variables was wrong after commenting out of line 32 in **install/index.php** and line 46 in **index.php** everything works fine.

was **install/index.php**

``` PHP
set_include_path(
    realpath('library')  . PATH_SEPARATOR
    . realpath('app/code') . PATH_SEPARATOR
    . get_include_path()
);
```

now **install/index.php**

```
set_include_path(
    realpath('library')  . PATH_SEPARATOR
    . realpath('app/code') . PATH_SEPARATOR
#    . get_include_path()
);
```
1. Is it possible to make these files more universal?
2. Is it ok to leave these lines commented?

**Comment by vladkrutov** [comment]
I think that's the same like Issue #48

**Comment by vovayatsyuk** [comment]
Yes, we think about this too. We will comment this line in the next release by default.

This paths are not used by the Axis, so it's ok.

**Comment by vladkrutov** [comment]
Many thanks.
