### ISSUE TITLE
Show SKU on product card.

### ISSUE THREAD

**Issue by vladkrutov** [axis/axiscommerce#163]
It is usefull to have option to show SKU on product card and to have abbility to search through it.

**Comment by vovayatsyuk** [comment]
You can output the product sku by changing the https://github.com/axis/axiscommerce/blob/develop/app/design/front/default/templates/catalog/index/product.phtml template.

Just copy it to app/design/front/custom/templates/catalog/index/product.phtml and add the following code:

```
<?php echo $this->escape($this->product['sku']);?>
```

Sku field is indexed in search module, so search by sku should works fine.

**Comment by vladkrutov** [comment]
Vova, thank you!

I already done it. like

```
        <div class="product-sku">
            <span> SKU: <?php echo $this->escape($this->product['sku']); ?></span>
        </div>
```

in custom folder, but i thought, that it can be useful to have option to switch it on or off in settings without codding. And also to have translations:
English - SKU
Russian - Артикул
etc...

**Comment by vovayatsyuk** [comment]
Fixed translation of the sku word: https://github.com/axis/axiscommerce/commit/6e150a199f087d83116014a8a6b7b8dc82eb6d6e

As for the option to show sku: It's too small change to make a separate config option to it and we don't want to add too many options right now.
