### ISSUE TITLE
Checkout is broken after last update

### ISSUE THREAD

**Issue by vovayatsyuk** [axis/axiscommerce#172]
Forum topic: http://axiscommerce.com/forum/blank-page-checkoutonestep

**Comment by vovayatsyuk** [comment]
Something wrong with receiving of the config option 'checkout/default_values/payment_method'

app/code/Axis/Checkout/Model/Checkout.php line 401

**Comment by ghost** [comment]
still have problem about this issues.
if Country_id_allow is set to 0, will can not choose "Country \* ",other thing seams is ok,
if Country_id_allow is set to other Country,such as 223(US) , thing will be ok,

**Comment by 0m3r** [comment]
closed the issue in  21a9f063cbe8c4c543f6455dc1bb49f3f5799a1f
