### ISSUE TITLE
CMS > Категории: некорректное использование значения полей

### ISSUE THREAD

**Issue by kehskas** [axis/axiscommerce#178]
Значения полей "Название" и "Ссылка" введенные в окне редактирования категории страниц модуля CMS, используются некорректно. Во фронтэнде, и в качестве ссылки и в качестве названия категории (по умолчанию, меню слева, и в breadcumbs) используется только значение из поля "Ссылка".

Корректно отображается только в бэкэнде.

**Comment by vovayatsyuk** [comment]
Название используется только для бекэнда, это поле не зависит от языка. На фронтенде отображается поле "Заглавие"
