### ISSUE TITLE
Вывод рубрик из helpers\Navigation.php

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#18]
У меня в массиве $items выводиться первый уровень и все под категории первой категории первого уровня, а все остальные подуровни не выводятся...
В новом сайте, в сайте по умолчанию все выводиться нормально.

**Comment by 0m3r** [comment]
Не удалось повторить.
связана ли эта проблема с #21? или они независимы ?
Вы хотите прикрепить теже категории к разным сайтам или как ? или же просто создали новое дерево а оно не отображается коректно?

**Comment by brokerUA** [comment]
С #21 не связана. Создаю новое дерево в каталоге товаров, в сайтах соответственно выбирается корневая рубрика.

Как повторить: добавить новый сайт, создать в новом дереве каталога товаров три рубрики с под рубриками. Выводиться будут только подрубрики первой категории, а подрубрики следующих категорий не выводятся. Так пробывали?

**Comment by 0m3r** [comment]
Итак не повторил :((, то-есть коректно у меня все. Даже не знаю. Давайте вместе разбираться. Смотрите в Axis_Catalog_Model_Category line 172, там вместо дурацкого $select; пишем 
Zend_Debug::dump($select->__toString());Zend_Debug::dump(func_get_args()); die;
можно также посмотреть добавляются ли коректно категории(рубрики) в таблицы  catalog_hurl и catalog_category

**Comment by brokerUA** [comment]
```
string(371) "SELECT `cc`.`id`, `cc`.`site_id`, `cc`.`lvl`, `cc`.`lft`, `cc`.`rgt`, `ccd`.`name`, `ch`.`key_word` FROM `catalog_category` AS `cc`
 LEFT JOIN `catalog_category_description` AS `ccd` ON ccd.category_id = cc.id AND ccd.language_id = :languageId
 LEFT JOIN `catalog_hurl` AS `ch` ON ch.key_id = cc.id WHERE (ch.key_type='c') AND (cc.site_id IN('2')) ORDER BY `cc`.`lft` ASC"

array(3) {
  [0] => string(1) "1"
  [1] => string(1) "2"
  [2] => bool(true)
}
```

в таблицах catalog_hurl и catalog_category категории присутствуют

**Comment by 0m3r** [comment]
Попробуйте пожалуйста выполнить запрос в каком нибудь mysql query browser (заменив :languageId на 2)

**Comment by brokerUA** [comment]
Выдало НЕ полный список рубрик, т.е. все первого уровня, а под рубрики только в первой категории.

**Comment by 0m3r** [comment]
значит нет там никаких под рубрик или как ?

**Comment by brokerUA** [comment]
Они есть, но данным запросом видимо не выводит.
может Вам будет удобнее, предоставить доступ к БД и фтп?

**Comment by 0m3r** [comment]
Посмотрите catalog_category_description таблицу если там на нужном языке название "под рубрик"

**Comment by brokerUA** [comment]
В системе только русский язык. В таблице catalog_category_description во всех рубриках в поле language_id установлена 1.
Сейчас использую сайт по-умолчанию, там все работает.
