### ISSUE TITLE
Невозможно открыть бокс для редактирования (дизайн/темы)

### ISSUE THREAD

**Issue by kehskas** [axis/axiscommerce#185]
На несколько секунд появляется заставка "Загрузка" и потом исчезает.

Что по двойному клику, что по клику на иконке редактирования. Один и то же результат что в default что в custom

**Comment by kehskas** [comment]
В демке 0.8.7 dev - открывается. Где подкрутить чтобы в 0.8.6 заработало?

**Comment by vovayatsyuk** [comment]
Закоментируйте [строку](https://github.com/axis/axiscommerce/blob/develop/.htaccess#L16) 16 в .htaccess файле:

```
#    RewriteRule ^(.+[^/])/$ http://%{HTTP_HOST}/$1 [R=301,L]
```
