### ISSUE TITLE
core/theme: ошибка при редактировании статического блока

### ISSUE THREAD

**Issue by kehskas** [axis/axiscommerce#189]
Закомментировал как сказано в issue #185  Окно редактирования открылось. Сменил название на кириллическое, больше ничего не менял, сделал сабмит "сохранить и продолжить" - выдает Warning: Invalid argument supplied for foreach() in app/code/Axis/Core/controllers/Admin/Theme/BlockController.php on line 107

Добавил значение в поле ссылка, вернул название по умолчанию, сделал все как было - ошибка осталась. После блок перестал выводиться совсем.

При повторном редактировании ошибки нет, но блок по прежнему не выводится.

**Comment by vovayatsyuk** [comment]
Ошибку повторить не могу (проверьте выключены ли у вас на сервере magic_quotes).

Скорее всего не сохранились привязки блока к странице. Откройте редактирование блока и посмотрите на первой вкладке грид с правилами вывода. Добавьте туда правила, если он пустой.

**Comment by kehskas** [comment]
MQ прописаны в php.ini перед установкой. Не могу выставить даже через список. Вываливается очередной Warning: Invalid argument supplied for foreach() in /app/code/Axis/Core/controllers/Admin/Theme/BlockController.php on line 140 значение привязки не сохраняется

**Comment by vovayatsyuk** [comment]
Чтобы разобраться почему параметр не декодируется нужно открыть файл /app/code/Axis/Core/controllers/Admin/Theme/BlockController.php и на строке 140 перед:

```
foreach ($dataset as $data) {
```

напишите следующее:

```
Axis::message()->addError(print_r($this->_getParam('data'), true));
return $this->_helper->json->sendSuccess();
```

И попробуйте еще раз привязать к любой странице через список.

Мой  результат:

```
{"67":{"id":67,"block":"left","box_status":1,"class":"Axis_Tag_Cloud","sort_order":100,"page_ids":"1,17","template_id":2}}
```

**Comment by kehskas** [comment]
Интересное кино. magic_quotes_gpc = On При установке настроил, проверил через phpinfo. Были Off.

0_о буду разбираться.

**Comment by kehskas** [comment]
Причина magic_quotes_gpc
Такое ощущение что была восстановлена старая версия .htaccess в которой отсутствовала конфигурация php
