### ISSUE TITLE
Релиз сырой axis-0.8.7.1! Не получается добавить новый товар

### ISSUE THREAD

**Issue by Serg3000** [axis/axiscommerce#194]
Не получается добавить новый товар. Это первый товар, который я хотел добавить в новую категорию.
Вот ошибка:

Notice: Undefined index: id in D:\localhost\app\code\Axis\Catalog\controllers\Admin\ProductController.php on line 390

Эта ошибка, скорей всего, от того, что отсутствует в карточке продукта вкладка Описание (как ее добавить?)

Но в предыдущем релизе axis-0.8.6 все ок (вкладка Описание там есть)!

Что это может быть, может кто сталкивался?

**Comment by vovayatsyuk** [comment]
Исправлено https://github.com/axis/axiscommerce/commit/17b4f3d4bc0da396698a64c3d1e75a32129ef1ad
