### ISSUE TITLE
Ошибка редактирования товара

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#2]
1. После внесения правок в товар он не сохраняется, пишет ошибку "Product sku must be unique value". При том что id этого товара уникален.
2. Создал новый сайт (admin/site). При создании товара в подкатегории магазина нового сайта, товару рубрика не применяется, он автоматически сбрасывается в корневую категорию магазина нового сайта.
3. В карточке товара нет поля ввода имени/описания товара, я так понимаю не подгружаеться /js/axis/admin/catalog/index/product/tabs/description.js. У меня первый таб SEO.

**Comment by vovayatsyuk** [comment]
1. Product sku - это не id товара. Обратите внимание на первое поле (SKU) на третьей вкладке продукта (inventory).
2. Да, есть проблема. Только продукт сохраняется корректно, это список продуктов не грузится.
3. Первой вкладкой должно идти описание. Попробуйте очистить кеш браузера и обновить старницу.

**Comment by brokerUA** [comment]
1. SKU (складской номер), должен быть уникален. Вот при редактировании товара скрипт не сохраняет изменения, а как бы добавляет новый товар и в результате пишет что SKU такой уже существует. Если изменить SKU то товар нормально сохраняется.
2. Ждем решения :)
3. Кеш обновлен, пробывал с разных браузеров. Так же заметил нет вкладки price.
   Инспектор в firebug при загрузке страницы пишет следующее:
   manufacturers is not defined
   [Break on this error] data: manufacturers,
   description.js (строка 80)
   taxClasses is not defined
   [Break on this error] data: taxClasses, 
   price.js (строка 83)

P.S. разверните к примеру на http://ecartcommerce.com/ обновленную версию, чтобы сравнивать с эталоном :)

**Comment by vovayatsyuk** [comment]
Понял, первая ошибка, это следствие третьей, у вас в запросе не передается id товара.
Спасибо за приведенные ошибки из фаербага, это важно.

P.S. В процессе.

**Comment by brokerUA** [comment]
Буду полностью тестировать проект, разрабатываем интернет-магазин на вашей системе. Оперативная связь с разработчиком очень важна, т.к. сроки сдачи не резиновые :)

**Comment by brokerUA** [comment]
Нашел в чем проблема, в скрипте отсутствует фильтрация одинарных кавычек.
У меня в таблице catalog_product_manufacturer был указан производитель 
     Name's.
Убрал кавычку, появились вкладки Описание и цена, а также нормально сохраняется.

Вопрос №2 остается открытый.
4. После указания любого поля Set As New From или Set As New To или Set As Featured From или Set As Featured To, его невозможно стереть (не сохраняется пустое, без указания даты). Временно выйти из ситуации можно указав дату окончания раньше чем дата начала, или стереть даты в БД.

**Comment by vovayatsyuk** [comment]
Исправлено.

**Comment by brokerUA** [comment]
- Сделайте при создании/редактировании товара выбор рубрики обязательным полем, т.к. если ее не указать товар сохраняется и отловить его можно только через СУБД. И создание с таким же SKU будет невозможно.
- сделать чтобы рубрика определялась автоматически, в зависимости от той категории которая выбрана в данный момент

**Comment by vovayatsyuk** [comment]
Товары вне категорий можно найти в ветке 'Uncategorized' - в дереве над всеми сайтами.
