### ISSUE TITLE
Переменная lastUrl в корзине

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#22]
При первом переходе в корзину значение переменной lastUrl правильное, изменив кол-во товара и нажав Update, переменная меняет значение на главную страницу сайта.
Как я понимаю lastUrl, находясь в корзине, должна всегда вести на последний открытый товар.

**Comment by vovayatsyuk** [comment]
Исправлено
https://github.com/axis/axiscommerce/commit/82238910ecb135a31109f2afdee21dc81f4c623d
