### ISSUE TITLE
Слетают подключенные атрибуты продукта при редактировании свойств категории

### ISSUE THREAD

**Issue by sk--an** [axis/axiscommerce#222]
Суть проблемы: создаем свои атрибуты в меню Каталог-Атрибуты продукта (набор размеров товара). После этого подключаем созданные атрибуты на вкладке Атрибуты свойств товара, назначаем цены вручную для каждого размера. Далее, если что-либо меняется в свойствах подкатегории, к которой  принадлежит продукт, например, загружается другой рисунок, меняется поле Ссылка или описание с последующим сохранением, на вкладке Атрибуты свойств товара пропадают добавленные атрибуты. В чем проблема, как ее исправить?

**Comment by vovayatsyuk** [comment]
При сохранении категории, таблицы продуктов не затрагиваются. Такое поведение невозможно.

Я протестировал ваш сценарий (изменил картинку и ссылку категории), и ни одна из опций продукта не пропала (характеристика, артибут, вариация)

**Comment by sk--an** [comment]
Проблему уже решили: ошибка нашего программиста, который делал изменения в коде. Спасибо.
