### ISSUE TITLE
Оформление заказа (шаг 5. Метод оплаты)

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#23]
Тестирую на локалке. На 4 шаге (способ доставки) оформления заказа нажимаю _продолжить_, появляется загрузка и ничего не происходит в логе следующее:
    2010-11-19T21:31:54+03:00 DEBUG (7): Notice: Use of undefined constant CURLOPT_HEADER - assumed 'CURLOPT_HEADER' in D:\xampp\htdocs___CMS_axis\library\Axis.php on line 115
    0 D:\xampp\htdocs___CMS_axis\library\Axis.php(115): AxisErrorHandler(8, 'Use of undefine...', 'D:\xampp\htdocs...', 115, Array)
    1 D:\xampp\htdocs___CMS_axis\app\code\Axis\PaymentPaypal\Model\Abstract.php(43): Axis::single('paymentPaypal/a...', 'Paypal_Direct')
    2 D:\xampp\htdocs___CMS_axis\app\code\Axis\PaymentPaypal\Model\Direct.php(42): Axis_PaymentPaypal_Model_Abstract->init()
    3 D:\xampp\htdocs___CMS_axis\library\Axis\Method\Abstract.php(52): Axis_PaymentPaypal_Model_Direct->init()
    4 D:\xampp\htdocs___CMS_axis\library\Axis\Method\Payment\Model\Abstract.php(51): Axis_Method_Abstract->__construct()
    5 D:\xampp\htdocs___CMS_axis\library\Axis\Payment.php(104): Axis_Method_Payment_Model_Abstract->__construct()
    6 D:\xampp\htdocs___CMS_axis\library\Axis\Payment.php(86): Axis_Payment::getMethod('Paypal_Direct')
    7 D:\xampp\htdocs___CMS_axis\library\Axis\Payment.php(129): Axis_Payment::getMethods()
    8 D:\xampp\htdocs___CMS_axis\app\code\Axis\Checkout\Controller\Checkout.php(148): Axis_Payment::getAllowedMethods(Array)
    9 D:\xampp\htdocs___CMS_axis\app\code\Axis\Checkout\controllers\OnepageController.php(204): Axis_Checkout_Controller_Checkout->paymentMethodAction()
    10 D:\xampp\htdocs___CMS_axis\library\Zend\Controller\Action.php(513): Axis_Checkout_OnepageController->paymentMethodAction()
    11 D:\xampp\htdocs___CMS_axis\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action->dispatch('paymentMethodAc...')
    12 D:\xampp\htdocs___CMS_axis\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
    13 D:\xampp\htdocs___CMS_axis\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
    14 D:\xampp\htdocs___CMS_axis\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
    15 D:\xampp\htdocs___CMS_axis\index.php(77): Zend_Application->run()
    16 {main}

Но, на хостинге все отлично работает, прохожу полный путь оформления заказа и в логах без ошибок.

**Comment by 0m3r** [comment]
установите curl на локальном сервере

**Comment by brokerUA** [comment]
Спасибо, заработало.
