### ISSUE TITLE
Отсутствуют подрубрики в cms

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#24]
Создал подрубрики в CMS, добавляю новую страницу, невозможно выбрать размещение в рубрике третьего уровня.
http://s41.radikal.ru/i093/1011/fe/48d3cfeb718a.jpg

**Comment by vovayatsyuk** [comment]
Там есть недоработка - список не обновляется при добавлении категорий. Попробуйте обновить страницу, должно сработать.

**Comment by brokerUA** [comment]
Обновил, появилось. Спасибо.
