### ISSUE TITLE
Problem Help me please

### ISSUE THREAD

**Issue by cosicomplus** [axis/axiscommerce#246]
Problem attribute and proprietes

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`shop`.`ax_catalog_product_attribute`, CONSTRAINT `FK_PRODUCT_ATTRIBUTE_VARIATION_ID` FOREIGN KEY (`variation_id`) REFERENCES `ax_catalog_product_variation` (`id`) ON DELETE CASCADE ON UPDATE )
Cannot refresh row as parent is missing

and

SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`shop`.`ax_catalog_product_attribute`, CONSTRAINT `FK_PRODUCT_ATTRIBUTE_VARIATION_ID` FOREIGN KEY (`variation_id`) REFERENCES `ax_catalog_product_variation` (`id`) ON DELETE CASCADE ON UPDATE )
Cannot refresh row as parent is missing
SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`shop`.`ax_catalog_product_attribute`, CONSTRAINT `FK_PRODUCT_ATTRIBUTE_VARIATION_ID` FOREIGN KEY (`variation_id`) REFERENCES `ax_catalog_product_variation` (`id`) ON DELETE CASCADE ON UPDATE )
Cannot refresh row as parent is missing

**Comment by eyeskiller** [comment]
I have same problem...

**Comment by eyeskiller** [comment]
I found soloution. You probably remove some variant and it set to ID 0. Create in database variant with ID: 0. This will temporary fix this problem.

**Comment by cosicomplus** [comment]
thank`s solved problem
