### ISSUE TITLE
Описание в admin/catalog_manufacturer

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#25]
По мимо названия еще желательно добавить описание производителя (поле типа html-editor wysiwyg) и чтобы эти данные выводились когда сортируется по бренду (пример: http://demo.axiscommerce.com/store/elektron/)

**Comment by brokerUA** [comment]
Добавление поля описание в мануфакторах
\js\axis\admin\catalog\manufacturer\window.js после 54 строчки добавлено
        }, {
            fieldLabel: 'Description'.l(),
            xtype: 'textarea',
            name: 'data[descr]',
            allowBlank: true

\app\code\Axis\Catalog\Model\Product\Manufacturer.php после 145 строчки добавлено
    $row['descr'] = empty($row['descr']) ? '' : $row['descr'];

в таблицу catalog_product_manufacturer добавлено поле
    `description` text NOT NULL,

сейчас такая таблица
    CREATE TABLE IF NOT EXISTS `catalog_product_manufacturer` (
      `id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
      `name` varchar(128) NOT NULL,
      `image` varchar(255) DEFAULT NULL,
      `description` text NOT NULL,
      PRIMARY KEY (`id`)
    ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC AUTO_INCREMENT=219 ;

**Подскажите что я еще пропустил чтобы нормально сохраняло поле _описание_ в админке**, фронтенд пока не трогал.

**Comment by brokerUA** [comment]
Как вывести в фронтенд разобрался.
В файле \library\Axis\HumanUri\Adapter\Readable.php после строчки 107 добавляем 
                    $this->_params['manufacturer']['description'] =
                        Axis::single('catalog/product_manufacturer')
                            ->select('description')
                            ->where('id = ?', $manufacturerId)
                            ->fetchOne();

далее в нужном файле шаблонов, в моем случае это \app\design\front\new\templates\catalog\index\listing.phtml, вставляем

```
$manuf = Axis_HumanUri::getInstance()->getParams();
echo $manuf['manufacturer']['description'];
```

**Comment by vovayatsyuk** [comment]
Если вы поменяли структуру таблицы, необходимо очистить кеш (admin/cache -> Clear all).

**Comment by brokerUA** [comment]
У меня кеш отключен полностью + очистил на всякий случай.
В админке после заполнения поля _Описание_ (добавленного в мануфакторы), выводит сообщение _Данные были успешно сохранены_, но данные не сохраняются. 
**Я видимо что-то пропустил для сохранения введенных данных.**

**Comment by vovayatsyuk** [comment]
Еще: вы создали поле в таблице description. 
Так почему же в других местах назвали его descr?

**Comment by brokerUA** [comment]
Не знал что переменная должна называться как поле таблицы.
Спасибо, заработало.

Выводит, сохраняет, но при редактировании мануфактора в админке не подгружает данные в поле описание. Ищу, разбираюсь...

**Comment by vovayatsyuk** [comment]
Нужно еще добавить описание поля в файл /js/axis/admin/catalog/manufacturer/grid.js

Смотрите строки 22-27

**Comment by brokerUA** [comment]
Спасибо за подсказку, описание реализовал (хоть и не совсем правильно, но работает) :)

**Comment by vovayatsyuk** [comment]
Сделано.
