### ISSUE TITLE
Ошибка регистрации

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#26]
При переходе на страницу /account/auth/register вовдит только
    <div class="page-title"><h1 class="title">аЁаОаЗаДаАб�б� б�б�аЕб�аНб�б� аЗаАаПаИб�б�</h1></div>
    <div class="register-box">
При комментировании <?php echo $this->formSignup->render($this) ?>
4строка в файле \app\design\front\default\templates\account\auth\register.phtml
страница выводиться но без формы.

Подскажите где искать ошибку вывода регистрации, как протестировать $this->formSignup->render($this). 
При оформлении заказа (checkout/onepage), вкладка регистрации открывается нормально.
В логах php пусто.

**Comment by vovayatsyuk** [comment]
Не могу повторить ошибку. 
Попробуйте блочно коментировать код в методе
Axis_Account_Model_Form_Signup::__construct() для нахождения проблемы. (Например строки от 112 до 190)

**Comment by brokerUA** [comment]
Проблема в этих строчках
файл app\code\Axis\Account\Model\Form\Signup.php (строки 190-196)
        $this->addElement('button', 'submit', array(
            'type' => 'submit',
            'class' => 'button',
            'label' => 'Register'
        ));

```
    $this->addActionBar(array('submit'));
```

При их комментировании форма отображается, но без кнопки submit

**Comment by brokerUA** [comment]
Изменил на
        $this->addElement('submit', 'submit', array(
заработало.

**Comment by brokerUA** [comment]
Этаже ошибка внутри аккаунта пользователя, метод исправления такой же.
Это у меня что-то или в скрипте была ошибка?

**Comment by vovayatsyuk** [comment]
Нет, была ошибка у нас: https://github.com/axis/axiscommerce/commit/fdfc1c53d23bead064ca25cee49de359cb411baa

Попробуйте теперь.

**Comment by brokerUA** [comment]
Спасибо, заработало.
