### ISSUE TITLE
Печать счетов

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#27]
На странице /admin/sales_order выбираю заказ и жму печать -> распечатать счет
перекидывает на пустую страницу с адресом /admin/sales_order/print
На http://demo.axiscommerce.com/admin/sales_order работает. 
Подскажите где искать ошибку? В php.log пусто.

Комментировал содержимое printAction() в файле \app\code\Axis\Admin\controllers\Sales, чтобы не выводило пустую страницу необходимо закомменитровать все содержимое printAction()

P.S. оплату через PayPal тестировали?

**Comment by vovayatsyuk** [comment]
Посмотрите системные логи apache, php. Возможна нехватка памяти.

Тестировали в песочнице. У вас возникли проблемы?

**Comment by brokerUA** [comment]
Через раз выводит Соединение было сброшено (из access.log "POST /___CMS_axis/admin/sales_order/print HTTP/1.1" 500 4), а в error.log
    [Tue Nov 30 15:01:31 2010] [notice] Parent: child process exited with status 255 -- Restarting.
    [Tue Nov 30 15:01:32 2010] [notice] Digest: generating secret for digest authentication ...
    [Tue Nov 30 15:01:32 2010] [notice] Digest: done
    [Tue Nov 30 15:01:34 2010] [notice] Apache/2.2.11 (Win32) DAV/2 mod_ssl/2.2.11 OpenSSL/0.9.8i PHP/5.2.9 configured -- resuming normal operations
    [Tue Nov 30 15:01:34 2010] [notice] Server built: Dec 10 2008 00:10:06
    [Tue Nov 30 15:01:34 2010] [notice] Parent: Created child process 4208
    [Tue Nov 30 15:01:37 2010] [notice] Digest: generating secret for digest authentication ...
    [Tue Nov 30 15:01:37 2010] [notice] Digest: done
    [Tue Nov 30 15:01:39 2010] [notice] Child 4208: Child process is running
    [Tue Nov 30 15:01:39 2010] [notice] Child 4208: Acquired the start mutex.
    [Tue Nov 30 15:01:39 2010] [notice] Child 4208: Starting 250 worker threads.
    [Tue Nov 30 15:01:39 2010] [notice] Child 4208: Starting thread to listen on port 443.
    [Tue Nov 30 15:01:39 2010] [notice] Child 4208: Starting thread to listen on port 80.

Но чаще выводит просто пустую страницу. В apach access.log и error.log пусто.

На локалке: memory_limit   32M
На хостинге тестировал, тоже не работает.

По PayPal тоже выводит пустую, но там стандартные данные оставлены, через песочницу пока не тестировал.

P.S. случайно нажал комментировать и закрыть, верните тему.

**Comment by 0m3r** [comment]
попробуйте сначала сгенерировать пдф поменьше, Print billing label etc. dompdf не удаляли ?
На счет paypal на белой странице должен срабатывать Javascript-овый редирект насколько я помню (Ctrl+U ?), какой именно paypal Вы тестируете ?

**Comment by brokerUA** [comment]
Print billing label сгенерировался только на хостинге (на локалке "Соединение было сброшено"), но в не правильной кодировке (пример: ÐÐ¼Ñ• Ð¤Ð°Ð¼Ð¸Ð»Ð¸Ñ•).

Подскажите какие настройки сервера необходимо провести, чтобы генерировались все пдф'ы и где указывать настройки кодировки пдф?

Пробывал PayPal Express, по нажатию кнопки подтвердить заказ перекидывает на пустую страницу /checkout/onepage/process (в Ctrl+U пусто).

Если не затруднит опишите рекомендуемый сервер и его настройки для использования axis commerce.

**Comment by 0m3r** [comment]
поcмотрите class Axis_Pdf локально у Вас может что-то не срабатывать ini_set к примеру попробуйте увеличить, уберите @

**Comment by 0m3r** [comment]
http://www.drupal.ru/node/36498

**Comment by 0m3r** [comment]
если стоит задача только печати, Вы можете отказатса от генерации пдфок
/app/code/Axis/Admin/controllers/Sales/OrderController.php line 330 
добавте   echo $content;die; 
дальше ctrl+p или <script type="text/javascript">window.print();</script> вставте в контент
на счет PayPal Express посмотрите /var/logs/payment.log

**Comment by brokerUA** [comment]
Отлично, спасибо, все генерирует (хтмл'ом) и печатает.

/var/logs/payment.log -- пустой.

**Comment by 0m3r** [comment]
опять же с пайпалом поправил не корректную работу с адресом доставки и форматом отображения а так у меня все работает

**Comment by brokerUA** [comment]
В локалке пробывал оплатить через PayPalExpress
выдало ошибку: Failure SetExpressCheckout 

Скорее всего проблемы из-за localhost и не совсем корректных введенных данных, попробую позже на хостинге с реальными данными...

в payment.log

```
2010-12-09T13:39:02+03:00 INFO (6):     Run SetExpressCheckout 
    AMT :30.00
    Return URL : http://localhost/__CMS_axis/paymentpaypal/express-checkout/details
    Cancel Url : http://localhost/__CMS_axis/paymentpaypal/express-checkout/cancel
    Options : <pre>array(11) {
  [&quot;CURRENCY&quot;] =&gt; string(3) &quot;RUB&quot;
  [&quot;PAYMENTACTION&quot;] =&gt; string(4) &quot;Sale&quot;
  [&quot;ADDROVERRIDE&quot;] =&gt; int(1)
  [&quot;SHIPTONAME&quot;] =&gt; string(23) &quot;Имя  Фамилия &quot;
  [&quot;SHIPTOSTREET&quot;] =&gt; string(0) &quot;&quot;
  [&quot;SHIPTOCITY&quot;] =&gt; string(11) &quot;Город &quot;
  [&quot;SHIPTOSTATE&quot;] =&gt; string(2) &quot;AL&quot;
  [&quot;SHIPTOZIP&quot;] =&gt; string(13) &quot;индекс &quot;
  [&quot;SHIPTOCOUNTRYCODE&quot;] =&gt; string(2) &quot;US&quot;
  [&quot;PHONENUM&quot;] =&gt; string(15) &quot;Телефон &quot;
  [&quot;SOLUTIONTYPE&quot;] =&gt; string(4) &quot;SOLE&quot;
}
</pre>
    Response : <pre>array(11) {
  [&quot;TIMESTAMP&quot;] =&gt; string(28) &quot;2010%2d12%2d09T10%3a32%3a49Z&quot;
  [&quot;CORRELATIONID&quot;] =&gt; string(13) &quot;d65374d423382&quot;
  [&quot;ACK&quot;] =&gt; string(7) &quot;Failure&quot;
  [&quot;VERSION&quot;] =&gt; string(5) &quot;3%2e2&quot;
  [&quot;BUILD&quot;] =&gt; string(7) &quot;1613703&quot;
  [&quot;L_ERRORCODE0&quot;] =&gt; string(5) &quot;10002&quot;
  [&quot;L_SHORTMESSAGE0&quot;] =&gt; string(39) &quot;Authentication%2fAuthorization%20Failed&quot;
  [&quot;L_LONGMESSAGE0&quot;] =&gt; string(67) &quot;You%20do%20not%20have%20permissions%20to%20make%20this%20API%20call&quot;
  [&quot;L_SEVERITYCODE0&quot;] =&gt; string(5) &quot;Error&quot;
  [&quot;CURL_ERRORS&quot;] =&gt; string(0) &quot;&quot;
  [&quot;in&quot;] =&gt; array(15) {
    [&quot;PAYMENTACTION&quot;] =&gt; string(4) &quot;Sale&quot;
    [&quot;ADDROVERRIDE&quot;] =&gt; int(1)
    [&quot;SHIPTONAME&quot;] =&gt; string(23) &quot;Имя  Фамилия &quot;
    [&quot;SHIPTOSTREET&quot;] =&gt; string(0) &quot;&quot;
    [&quot;SHIPTOCITY&quot;] =&gt; string(11) &quot;Город &quot;
    [&quot;SHIPTOSTATE&quot;] =&gt; string(2) &quot;AL&quot;
    [&quot;SHIPTOZIP&quot;] =&gt; string(13) &quot;индекс &quot;
    [&quot;SHIPTOCOUNTRYCODE&quot;] =&gt; string(2) &quot;US&quot;
    [&quot;PHONENUM&quot;] =&gt; string(15) &quot;Телефон &quot;
    [&quot;SOLUTIONTYPE&quot;] =&gt; string(4) &quot;SOLE&quot;
    [&quot;AMT&quot;] =&gt; string(5) &quot;30.00&quot;
    [&quot;RETURNURL&quot;] =&gt; string(80) &quot;http%3A%2F%2Flocalhost%2F__CMS_axis%2Fpaymentpaypal%2Fexpress-checkout%2Fdetails&quot;
    [&quot;CANCELURL&quot;] =&gt; string(79) &quot;http%3A%2F%2Flocalhost%2F__CMS_axis%2Fpaymentpaypal%2Fexpress-checkout%2Fcancel&quot;
    [&quot;METHOD&quot;] =&gt; string(18) &quot;SetExpressCheckout&quot;
    [&quot;CURRENCYCODE&quot;] =&gt; string(3) &quot;RUB&quot;
  }
}
</pre>
2010-12-09T13:39:02+03:00 INFO (6): 
    Failure SetExpressCheckout
```

**Comment by 0m3r** [comment]
а NVP Вы настроили ? (: Ну в смисле API Signature -- Password  etc.
https://www.x.com/thread/39470
