### ISSUE TITLE
Ошибка перемещения категорий CMS

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#28]
При перетаскивании одной рубрики CMS в другую выдают ошибку:

Warning: Missing argument 2 for Zend_Db_Adapter_Abstract::quoteInto(), called in D:\xampp\htdocs\CMS_axis\app\code\Axis\Admin\controllers\Cms\IndexController.php on line 215 and defined in D:\xampp\htdocs\CMS_axis\library\Zend\Db\Adapter\Abstract.php on line 899

**Comment by vovayatsyuk** [comment]
Исправлено
