### ISSUE TITLE
Ошибка в карточке товара после правок

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#29]
После внесения правок с 2010-11-30, при переходе в карточку товара выдает ошибку.
php.log:
    2010-12-02T16:21:19+03:00 DEBUG (7): SQLSTATE[42S22]: Column not found: 1054 Unknown column 'relation_categories' in 'field list'
    #0 D:\xampp\htdocs___CMS_axis\library\Zend\Db\Statement.php(300): Zend_Db_Statement_Pdo->_execute(Array)
    #1 D:\xampp\htdocs___CMS_axis\library\Zend\Db\Adapter\Abstract.php(468): Zend_Db_Statement->execute(Array)
    #2 D:\xampp\htdocs___CMS_axis\library\Zend\Db\Adapter\Pdo\Abstract.php(238): Zend_Db_Adapter_Abstract->query('SELECT relation...', '120')
    #3 D:\xampp\htdocs___CMS_axis\library\Zend\Db\Adapter\Abstract.php(799): Zend_Db_Adapter_Pdo_Abstract->query('SELECT relation...', '120')
    #4 D:\xampp\htdocs___CMS_axis\library\Axis\Db\Table\Abstract.php(266): Zend_Db_Adapter_Abstract->fetchOne('SELECT relation...', '120')
    #5 [internal function]: Axis_Db_Table_Abstract->__call('getRelationCate...', Array)
    #6 D:\xampp\htdocs___CMS_axis\app\code\Axis\Catalog\Model\Product\Row.php(476): Axis_Catalog_Model_Category->getRelationCategoriesByProductId('120', NULL)
    #7 D:\xampp\htdocs___CMS_axis\app\code\Axis\Catalog\controllers\IndexController.php(264): Axis_Catalog_Model_Product_Row->getParentItems('44')
    #8 D:\xampp\htdocs___CMS_axis\app\code\Axis\Catalog\controllers\IndexController.php(108): Axis_Catalog_IndexController->productAction()
    #9 D:\xampp\htdocs___CMS_axis\library\Zend\Controller\Action.php(513): Axis_Catalog_IndexController->viewAction()
    #10 D:\xampp\htdocs___CMS_axis\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action->dispatch('viewAction')
    #11 D:\xampp\htdocs___CMS_axis\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
    #12 D:\xampp\htdocs___CMS_axis\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
    #13 D:\xampp\htdocs___CMS_axis\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
    #14 D:\xampp\htdocs___CMS_axis\index.php(77): Zend_Application->run()
    #15 {main}

**Comment by vovayatsyuk** [comment]
В репозитории такого вызова нету:

<a href="/axis/axiscommerce/issues/#issue/6" class="internal">#6</a> D:\xampp\htdocs___CMS_axis\app\code\Axis\Catalog\Model\Product\Row.php(476): Axis_Catalog_Model_Category->getRelationCategoriesByProductId('120', NULL)

https://github.com/axis/axiscommerce/blob/master/app/code/Axis/Catalog/Model/Product/Row.php#L476
Обновитесь до последней версии

**Comment by brokerUA** [comment]
Обновил, спасибо, заработало.
