### ISSUE TITLE
Размер превью загруженной картинки для рубрики каталога

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#3]
Сейчас в превью загруженной картинке выводиться следующее:
     <a target="_blank" href="__путь к загруженной картинке__" class="x-form-file-preview" id="ext-gen244" >
          <img height="22" width="22" src="__путь к загруженной картинке__" id="ext-gen245">
     </a>

чтобы не было той непонятно маленькой картинки 22х22, предлагаю следующее решение:

```
 <a target="_blank" href="__путь к загруженной картинке__" class="x-form-file-preview" id="ext-gen244" style="text-align: center; margin-bottom: 5px; overflow: hidden; width: 215px;">
      <img src="__путь к загруженной картинке__" id="ext-gen245" alt=""/>
 </a>
```

Но в идеале, было бы неплохо делать авто ресайз картинки, для отображения превью.

P.S. плохо что здесь нельзя прикреплять скриншоты, указывать паритетность задач...

**Comment by vovayatsyuk** [comment]
22 - высота стандартного елемента формы. Ресайз добавлять не будем - лишняя нагрузка, да и в админке он не нужен.
Но если очень нужно картинки побольше - вынес размеры картинки из кода в css файл. Можете создать отдельную тему и применить ее для админки.
