### ISSUE TITLE
Ошибка в админке (каталог товров) после правок

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#30]
Захожу в админку (каталог товаров), не выводит таблицу рубрик и товаров,
пример http://s60.radikal.ru/i169/1010/df/04ad86539aed.jpg (ошибки на скрине старые)

Новые ошибки:
    Ошибка: Axis.grid.Filter is not a constructor
    Источник: http://localhost/___CMS_axis/js/axis/admin/catalog/index/product/grid.js
    Строка: 387

```
Ошибка: a is undefined
Источник: http://localhost/___CMS_axis/js/ext-3.2.1/ext-all.js
Строка: 7
```

**Comment by vovayatsyuk** [comment]
Отключите сжатие скриптов и стилей, если включено.
Обновите страницу через Ctrl+F5
Посмотрите в исходной код странице, подключается ли скрипт js/ext-axis/src/widgets/grid/Filter.js

**Comment by brokerUA** [comment]
Configuration -> Core -> Minify -> Enable javascript merging on the backend 
установлено в No

Обновлял страницу /admin/catalog_index (Ctrl+Shift+R)

В исходном коде js/ext-axis/src/widgets/grid/Filter.js отсутствует.

**Comment by vovayatsyuk** [comment]
В файле https://github.com/axis/axiscommerce/blob/master/app/design/admin/default/layouts/layout.phtml#L85 должна быть строка ->offsetSetFile(-14, 'js/ext-axis/src/widgets/grid/Filter.js');

Также должен быть файл https://github.com/axis/axiscommerce/blob/master/js/ext-axis/src/widgets/grid/Filter.js

Посмотрите есть ли такие у вас.

**Comment by brokerUA** [comment]
Добавил строчку offsetSetFile(-14, 'js/ext-axis/src/widgets/grid/Filter.js'); в соответствующий файл. Непонятно, вносил ведь все новые обновления.
Заработало, спасибо за помощь.
