### ISSUE TITLE
Баг FF&Opera отображения мессенжера в админке.

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#31]
В админке появление строки сообщений (блок #messages) приводит к появлению горизонтального скроллбара, а при клике по блоку он исчезает и скролл тоже.
Так же растягивается таблица с данными и при исчезновении блока сообщений становить нормальной ширины

В Opera также, только не появляется горизонтальный скроллбар.

В IE8 все ок.

**Comment by vovayatsyuk** [comment]
Исправлено
