### ISSUE TITLE
Zones Definitions — SQLSTATE[HY093]...

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#32]
Поясните, пожалуйста, для чего нужен раздел Zones Definitions в админке?

К примеру создал в левой колонке
Name: Украина
Description: Украина
Priority: 10

Выделил созданную строку и нажал **Load Zones**
Далее в правой колонке **Add** и Country: Ukraine, Zone: Запорожская (Запорожскую область предварительно создал в разделе зон).
Жму **Save**, в ответ ошибка:
**SQLSTATE[HY093]: Invalid parameter number: no parameters were bound**

**Comment by 0m3r** [comment]
Zones Definitions используется при создании налогов пример для Евросоюза такая то ставка ПДВ. Также зону можно указывать в способе оплаты и доставки 
к примеру "новая почта" действует только для каких то областей - создайте зону с этими областями и в конфиге указываете ее.

**Comment by 0m3r** [comment]
https://github.com/axis/axiscommerce/commit/ffce9ada09a6794b21f28d3a0352ac7be57064cc
