### ISSUE TITLE
Не удаляются опросы

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#33]
Захожу _/admin/poll_index_, выделил, нажал удалить.

Очистились поля id, Questions, Created, Modified
Status: не отмечена
Type: SingleSelect
Votes: 0

Строчки опросов остались.

**Comment by 0m3r** [comment]
Не смог я воссоздать ошибку, правда пофиксал мультиселект в гриде (сайт)
commit 'fix Ext.ux.Andrie.Select calls' может поможет Вам
