### ISSUE TITLE
Установка на сервер. Чистая страница.

### ISSUE THREAD

**Issue by oksar** [axis/axiscommerce#34]
При запуске инсталла на хостинге -выходит просто чистая страница, никаких ошибок, права на файлы пробовал все. При установке на компьютере всё нормально. Если перенести уже готовый, инсталлированный магазин с локалки на хостинг, какие конфигурационные файлы нада править и где они находятся?

**Comment by vovayatsyuk** [comment]
Была такая проблема (https://github.com/axis/axiscommerce/commit/f9548aefe75169361847d78275c6f81569c59b5e), если нету прав на запись в директорию var.

Попробуйте выполнить chmod 0777 -R AXIS_ROOT/var

При переносе нужно отредактировать файл AXIS_ROOT/app/etc/config.php, а также поправить значения в таблице core_site

**Comment by oksar** [comment]
Права на запись не решили проблему. Даже при переносе магазина с локалки на хостинг, также белая страница. Проблема в хостинге?

**Comment by vovayatsyuk** [comment]
Нужно смотреть логи сервера

**Comment by oksar** [comment]
В логах сервера чисто. Проблема решена переносом на другой хостинг.
