### ISSUE TITLE
Import osCommerce

### ISSUE THREAD

**Issue by oksar** [axis/axiscommerce#35]
Выбираем импорт osCommerce, соединение с импортируемой базой происходит нормально, выбираем русский язык. Таблицы базы данных osCommerce в кодировке cp1251, после импорта к примеру товаров - вместо букв отображаются знаки вопросов. Перекодировка таблицы в ut8 не помогла.

**Comment by vovayatsyuk** [comment]
Возможно поможет это изменение https://github.com/axis/axiscommerce/commit/8d2f843448b23d8f44c1e22143dd91b1d19ffef2
Но там есть еще проблема, creloaded сохраняет кирилицу как ascii символы (моя версия так делает). Так что нужно будет еще переводить ascii в unicode

**Comment by oksar** [comment]
С русским языком всё нормально, но импортирует буквально один товар и выдает: 
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'название товара1' for key 'PRIMARY

**Comment by vovayatsyuk** [comment]
Исправил проверку на дубликаты https://github.com/axis/axiscommerce/commit/ec34b129ff7a3da0f63354d6f51256c7b325ad62

**Comment by oksar** [comment]
Всё работает на ура! Отличный скрипт!
