### ISSUE TITLE
Ссылки на подкатегории в самой категории

### ISSUE THREAD

**Issue by oksar** [axis/axiscommerce#36]
Каталог состоит из категорий товаров и подкатегорий. В демо, в категориях, состоящих из подкатегорий показываются товары из подкатегорий. Есть ли модуль-бокс выводящий в категории по центру список -ссылки на подкатегории этой категории?

**Comment by vovayatsyuk** [comment]
Товары из подкатегорий не отображаются. Эти товары включены в несколько категорий.

Такого модуля из коробки пока нету. 

Вот тут можете посмотреть/скачать такой модуль: https://github.com/axis/axiscommerce_examples (Example_Catalog_Box_Subcategory)

Еще вы наверное захотите вывести список категорий под названием категории и ее рисунком. Для этого отредактируйте файл /axis/app/design/front/default/templates/catalog/index/listing.phtml. 
После строки 16 добавьте:

```
<?php echo $this->layout()->beforeProductList ?>
```

А в админке при добавлении бокса в колонке контейнер (layout block) укажите beforeProductList.

Как еще можно вывести блок написано тут http://axiscommerce.com/blog/minimal-module-example

**Comment by oksar** [comment]
Спасибо огромное, все получилось..
