### ISSUE TITLE
Процесс оформления заказа-способ доставки

### ISSUE THREAD

**Issue by oksar** [axis/axiscommerce#37]
При оформлении заказа, на шаге способа доставки , появляется _Мы не можем доставить товар по указанному адресу_. На демо-сайте Axis пробую- всё нормально, настройки shipping methods у меня такие же как и на демо. В чем может быть проблема?

**Comment by vovayatsyuk** [comment]
На отображение методов доставки влияют настройки enabled и geozone каждого из методов.

Если вы что-то изменяли в настройках, очистите кеш "config" (admin/cache)

**Comment by oksar** [comment]
Везде стоит ALL , на нескольких способах Enabled стоит yes, кэш почистил. проблема осталась.

**Comment by vovayatsyuk** [comment]
Посмотрите admin/location_geozone.
Загрузите геозону ALL. Там должна быть одна строка:
- Страна: ALL WORLD COUNTRY
- Область: ALL ZONES

**Comment by oksar** [comment]
Область пропустил, заработало. ..И ещё вопрос, есть ли в стандартной сборке модуль вертикального меню категорий товаров и где находятся файлы шаблона и как подключить новый шаблон?..заранее благодарен!

**Comment by vovayatsyuk** [comment]
Разместите еще один бокс навигации в колонку - к нему применятся необходимые стили.

Если хотите менять стили, шаблоны - создайте отдельную тему оформления (admin/template_index - создать шаблон), затем в конфигурации выберите новую тему (design/main/frontTemplateId).

Затем создайте папки
- app/design/front/названиеТемы
- skin/front/названиеТемы

Копируйте в эти папки файлы, которые нуждаются в изменениях (с сохранением вложенных папок). Остальные будут подключаться из темы fallback и default.

**Comment by oksar** [comment]
Есть ли уведомление администратора на email о новых заказах и отсылается ли клиенту дубликат такого письма о его заказе?..Если есть..где это включить?...просмотрел конфигурацию - не нашел. Ещё вопрос..возможна ли доработка, написание необходимых модулей, темплэйтов Вами за плату?

**Comment by vovayatsyuk** [comment]
Уведомление есть, но оно было закомментировано. Исправлено здесь https://github.com/axis/axiscommerce/commit/040558dda63e4289a0ca0f05fea9956c6724a119

Нет, мы полностью заняты разработкой движка.

**Comment by oksar** [comment]
ошибка в файле app/design/mail/order_new-customer_html.phtml
67 строка <a href="<?php echo $this->href('/account/order/view/orderId/' . $this->order->ird, true)?>" style="color:#1E7EC8;"

**Comment by 0m3r** [comment]
fixed
