### ISSUE TITLE
Название брэнда в карточке товара

### ISSUE THREAD

**Issue by oksar** [axis/axiscommerce#39]
Есть ли возможность вывода производителя-брэнда в списке товаров (допустим под фотографией) и на странице товара?...было бы замечательно, чтоб выводился небольшой логотип.

**Comment by vovayatsyuk** [comment]
Такая возможность есть на странице продукта. 

```
<?php print_r($this->product['manufacturer']) ?>
```

Рисунок можно выводить через imager хелпер по аналогии продукта:
    <?php 
    $image = $this->product['manufacturer']['image'];
    $title = $this->product['manufacturer']['title'];
    $url   = $this->hurl(array(
        'controller'      => 'catalog',
        'action'          => 'view',
        'manufacturer' => array(
            'value' => $this->product['manufacturer']['id'], 
            'seo'   => $this->product['manufacturer']['key_word']
        )
    ), false, true)
    ?>
    <a href="<?php echo $url ?>" title="<?php echo $this->escape($title) ?>"
        ><?php echo $this->imager('manufacturer' . $image, array(
        'width'  => 100,
        'height' => 100,
        'title'  => $this->escape($title),
        'alt'    => $this->escape($title)
    )) ?>
    </a>

В списке товаров данные производителя не загружаются - только id.

**Comment by oksar** [comment]
Страница продукта /app/design/front/default/templates/catalog/index/product.phtml ?

**Comment by vovayatsyuk** [comment]
да, product.phtml

**Comment by oksar** [comment]
Да...и ещё такой вопрос. Необходим вывод SKU (артикула-модели) также на странице товара.

**Comment by vovayatsyuk** [comment]
```
<?php echo $this->product['sku'] ?>
```

**Comment by oksar** [comment]
Всё...спасибо огромное!...я понял метод вывода значений на этих примерах.
