### ISSUE TITLE
Ошибки Manufacturer

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#4]
Когда выводиться список производителей, они берутся со всех сайтов сразу (у меня через admin/site создано два сайта), и на выходе один и тот же производитель повторяется столько раз сколько создано сайтов.

Временный выход из ситуации:
в файл \app\code\Axis\Catalog\Model\Product\Manufacturer.php изменить строчку 53 на
    "ch.key_type = 'm' AND ch.key_id = cpm.id AND ch.site_id = 1",
В идеале, вместо единицы нужно передать переменную с id сайта.

P.S. так же не понятно, создал отдельный сайт, а как его применить чтобы он отображался вместо сайта по умолчанию? в конфигурации не нашел выбора текущего сайта.

**Comment by vovayatsyuk** [comment]
Исправлено.

Текущий сайт определяется по ссылке.

**Comment by brokerUA** [comment]
Спасибо за исправления.

Но с текущим сайтом проблема не решена. У меня создано два сайта
    | 1 | Main Store | http://localhost/ | http://localhost/ | Main Store
    | 2 | New Store | http://localhost/___CMS_axis | http://localhost/___CMS_axis | New Store
При заходе на http://localhost/___CMS_axis все данные выводятся из Main Store и все url стилей и т.п. указывается http://localhost/, т.е. текущий сайт не определяется по ссылке... может я что-то не правильно указываю?

**Comment by vovayatsyuk** [comment]
Такие ссылки не обрабатывались. Теперь должно работать корректно: http://github.com/axis/axiscommerce/commit/848e42d01a15ea7db7f3e3c98e011f4464fa9cfa

**Comment by brokerUA** [comment]
Сайты заработали, вот только при переходе по любому товару выводит следующую ошибку

```
* Cannot open file. Permission denied

An error has occured processing your request

* The server encountered an internal error or misconfiguration and was unable to complete your request.
* More information about this error may be available in the server error log.

Copyright © 2008, Axis, Inc. All Rights Reserved

Report any Bugs or Issues you've found
```

**Comment by vovayatsyuk** [comment]
Полный текст ошибки должен выводится в файл AXIS_ROOT/var/logs/php.log.

**Comment by brokerUA** [comment]
<pre>
2010-10-14T17:39:37+04:00 DEBUG (7): Notice: Trying to get property of non-object  in D:\xampp\htdocs\___CMS_axis\app\code\Axis\Catalog\controllers\IndexController.php on line 277
#0 D:\xampp\htdocs\___CMS_axis\app\code\Axis\Catalog\controllers\IndexController.php(277): AxisErrorHandler(8, 'Trying to get p...', 'D:\xampp\htdocs...', 277, Array)
#1 D:\xampp\htdocs\___CMS_axis\app\code\Axis\Catalog\controllers\IndexController.php(101): Axis_Catalog_IndexController->productAction()
#2 D:\xampp\htdocs\___CMS_axis\library\Zend\Controller\Action.php(513): Axis_Catalog_IndexController->viewAction()
#3 D:\xampp\htdocs\___CMS_axis\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action->dispatch('viewAction')
#4 D:\xampp\htdocs\___CMS_axis\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#5 D:\xampp\htdocs\___CMS_axis\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()
#6 D:\xampp\htdocs\___CMS_axis\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#7 D:\xampp\htdocs\___CMS_axis\index.php(75): Zend_Application->run()
#8 {main}
</pre>

**Comment by vovayatsyuk** [comment]
Поправил еще раз :)

**Comment by brokerUA** [comment]
Ошибка осталась

<pre>
2010-10-14T18:19:34+04:00 DEBUG (7): Notice: Undefined variable: relativePath in D:\xampp\htdocs\___CMS_axis\library\Axis\View\Helper\SkinUrl.php on line 48
#0 D:\xampp\htdocs\___CMS_axis\library\Axis\View\Helper\SkinUrl.php(48): AxisErrorHandler(8, 'Undefined varia...', 'D:\xampp\htdocs...', 48, Array)
#1 D:\xampp\htdocs\___CMS_axis\library\Zend\View\Abstract.php(342): Axis_View_Helper_SkinUrl->skinUrl('images/no_image...')
#2 [internal function]: Zend_View_Abstract->__call(Array, Array)
#3 D:\xampp\htdocs\___CMS_axis\library\Axis\View\Helper\Imager.php(146): Zend_View->skinUrl('skinUrl', Array)
#4 D:\xampp\htdocs\___CMS_axis\library\Zend\View\Abstract.php(342): Axis_View_Helper_Imager->imager('images/no_image...')
#5 [internal function]: Zend_View_Abstract->__call('/product', Array)
#6 D:\xampp\htdocs\___CMS_axis\app\design\front\sephora\templates\catalog\index\product\media.phtml(20): Zend_View->imager(Array, Array)
#7 D:\xampp\htdocs\___CMS_axis\library\Zend\View.php(108): include('D:\xampp\htdocs...')
#8 D:\xampp\htdocs\___CMS_axis\library\Zend\View\Abstract.php(880): Zend_View->_run('imager', Array)
#9 D:\xampp\htdocs\___CMS_axis\app\design\front\sephora\templates\catalog\index\product.phtml(5): Zend_View_Abstract->render('/product', Array)
#10 D:\xampp\htdocs\___CMS_axis\library\Zend\View.php(108): include('D:\xampp\htdocs...')
#11 D:\xampp\htdocs\___CMS_axis\library\Zend\View\Abstract.php(880): Zend_View->_run('D:/xampp/htdocs...')
#12 D:\xampp\htdocs\___CMS_axis\library\Zend\Controller\Action.php(219): Zend_View_Abstract->render('index/product/m...')
#13 D:\xampp\htdocs\___CMS_axis\app\code\Axis\Catalog\controllers\IndexController.php(342): Zend_Controller_Action->render('D:/xampp/htdocs...')
#14 D:\xampp\htdocs\___CMS_axis\app\code\Axis\Catalog\controllers\IndexController.php(101): Axis_Catalog_IndexController->productAction('index\product.p...')
#15 D:\xampp\htdocs\___CMS_axis\library\Zend\Controller\Action.php(513): Axis_Catalog_IndexController->viewAction('product')
#16 D:\xampp\htdocs\___CMS_axis\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action->dispatch()
#17 D:\xampp\htdocs\___CMS_axis\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch()
#18 D:\xampp\htdocs\___CMS_axis\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch('viewAction')
#19 D:\xampp\htdocs\___CMS_axis\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#20 D:\xampp\htdocs\___CMS_axis\index.php(75): Zend_Application->run()
#21 {main}
</pre>

**Comment by brokerUA** [comment]
Заработало, причина прошлой ошибки не понятна, просто добавил картинку в товар а потом удалил...

**Comment by vovayatsyuk** [comment]
Исправил эту тоже.
