### ISSUE TITLE
Ошибка в админке Action "getItems" does not exist and was not trapped in __call()

### ISSUE THREAD

**Issue by oksar** [axis/axiscommerce#41]
В админской панеле, при переходе Администрирование-сайт вылазит следующая ошибка Action "getItems" does not exist and was not trapped in __call(), при этом список сайтов пустой.

**Comment by vovayatsyuk** [comment]
getItems is undefined. Closed by 0641c6b0c01ef7d52b7683bcb22fafa51d2619a2
