### ISSUE TITLE
Титл страниц. 

### ISSUE THREAD

**Issue by oksar** [axis/axiscommerce#42]
По умолчанию титл страниц выглядит следующим образом: Page title - Site name? Можно ли изменить порядок на Название сайта (Site name) - Название страницы (page title)?

**Comment by vovayatsyuk** [comment]
Пока такой возможности нету.
Решение:
- Скопируйте хелпер Мета из /library/Axis/View/Helpe/Meta.php в /app/design/front/fallback/helpers/Meta.php
- Теперь для магазина будет взят хелпер из папки фолбек
- Смените 84 строчку на

:

```
foreach (array('site name', 'page title') as $titlePart) {
```

Еще в этот массив можно добавить 'parent page titles'
