### ISSUE TITLE
Список подкатегорий.

### ISSUE THREAD

**Issue by oksar** [axis/axiscommerce#43]
Список подкатегорий выводится в виде ненумерованного списка. 
Код subcategory.phtml: 
    <ul class="box-subcategory">
    <?php foreach ($this->box->categories as $category) : ?>
    <?php $url = $this->hurl(array(
        'cat'           => array(
            'value' => $category['id'],
            'seo'   => $category['key_word']
        ),
        'controller'    => 'catalog',
        'action'        => 'view'
    ), false/_non-ssl link_/, true/_reset url params_/) ?>
    <li>
        <a href="<?php echo $url ?>" title="<?php echo $category['name'] ?>"
            ><?php echo $this->imager('category' . $category['image_listing'], array(
                'width'     => 150,
                'height'    => 150,
                'alt'       => $this->escape($category['image_base_title']),
                'seo'       => $category['image_base_title']
            )); ?><br><?php echo $category['name'] ?></a>
    </li>
    <?php endforeach; ?>
    </ul>
Как вывести список субкатегорий не в виде списка, а в виде таблицы из двух или трех колонок?

**Comment by vovayatsyuk** [comment]
Воспользуйтесь примером вывода списка продуктов: 
    app/design/front/default/templates/catalog/index/listing.phtml
Строки 110 - 206

**Comment by oksar** [comment]
Кому интересно, это будет выглядеть примерно так:
 <table class="category-listing category-listing-table" id="category-listing-table">
    <?php 
    $i = 0;
    $columnCount = 3; 
    foreach ($this->box->categories as $category) : ?>
    <?php $url = $this->hurl(array(
        'cat'           => array(
            'value' => $category['id'],
            'seo'   => $category['key_word']
        ),
        'controller'    => 'catalog',
        'action'        => 'view'
    ), false/_non-ssl link_/, true/_reset url params_/) ?>
            <?php if ($i%$columnCount == 0) : ?>
           <tr>
        <?php endif; ?>
            <td align="center">
                <div class="product-item">
        <a href="<?php echo $url ?>" title="<?php echo $category['name'] ?>"
            ><?php echo $this->imager('category' . $category['image_listing'], array(
                'width'     => 150,
                'height'    => 150,
                'alt'       => $this->escape($category['image_base_title']),
                'seo'       => $category['image_base_title']
            )); ?><br><b><?php echo $category['name'] ?></b></a>
                </div>
            </td>
       <?php $i++;

```
    if ($i%$columnCount==0) : ?>
       </tr>
    <?php endif;

endforeach;

if ($i % $columnCount != 0) :
    for($i; $i % $columnCount; $i++): ?>
        <td class="empty-cell">&nbsp;</td>
    <?php 
    endfor;?>
    </tr>
<?php endif; ?>

</table>
```
