### ISSUE TITLE
Ошибка после commit  4bdc4241895ecda8ee0c

### ISSUE THREAD

**Issue by oksar** [axis/axiscommerce#45]
После последних исправлений, при переходе в админке Администрирование-Конфигурация таблица настроек пустая и вылазит ошибка: Unrecognized method 'addValue()' . Скорее всего ошибка в файле app/code/Axis/Admin/controllers/ConfigurationController.php

**Comment by vovayatsyuk** [comment]
Проверьте модель app/code/Axis/Core/Model/Config/Field.php

В 42ой строчке должна быть запись:

```
protected $_selectClass = 'Axis_Core_Model_Config_Field_Select';
```

Также посмотрите есть ли сама модель здесь:

```
app/code/Axis/Core/Model/Config/Field/Select.php
```

**Comment by oksar** [comment]
Нет ни того ни другого.

**Comment by vovayatsyuk** [comment]
Значит у вас частично новая ревизия (контроллер), а частично старая (модели).

**Comment by oksar** [comment]
Замена файлов на файлы из latest version from repo решат проблему? Файлы выложенные в данную минуту включают коммиты за последний час? или изменения делать вручную ?

**Comment by vovayatsyuk** [comment]
Да, ветка мастер включает в себя последние обновления.
