### ISSUE TITLE
Комментарий к заказу.

### ISSUE THREAD

**Issue by oksar** [axis/axiscommerce#46]
На форуме аксиса человек внес хорошее предложение. Было бы неплохо, чтобы клиент при оформлении заказа мог оставлять комментарий к своему заказу. Для этого сделать дополнительное текстовое поле (Комментарий), куда бы клиент вводил комментарий . Например _Меня не будет дома с такого-то по такое время или код домофона для курьера при доставке, или свои реквизиты при безналичной оплате_.

**Comment by vovayatsyuk** [comment]
Сделано.
