### ISSUE TITLE
Ошибка при оформлении заказа- комментарии к заказу.

### ISSUE THREAD

**Issue by oksar** [axis/axiscommerce#47]
После обновления файлов, при оформлении заказа выдает ошибку Specified column "customer_comment" is not in the row. Я так понимаю, что отсутсвует в базе таблица customer_comment? Какие выполнить sql запросы к базе данных для создания таблицы? Выполнение следующих запросов проблему не решают:  

```
 ALTER TABLE sales_order
        ADD COLUMN customer_comment TEXT AFTER site_id,
        ADD COLUMN admin_comment TEXT AFTER customer_comment;
```

**Comment by vovayatsyuk** [comment]
Все необходимые изменения включены в обновление. Вам нужно только их запустить: www.example.com/admin/module - нажмите обновить все.

Если вы вручную добавили колонки - удалите их перед применением обновления.

**Comment by oksar** [comment]
Обновил, ошибка всё-равно выходит на последнем шаге оформления заказа: Specified column "customer_comment" is not in the row

**Comment by vovayatsyuk** [comment]
Попробуйте очистить кеш. Дело в том, что кеш на структуру таблиц создается даже с выключенным кешем. admin/cache/clean-all

**Comment by oksar** [comment]
Очистка кэша помогла, спасибо огромное.
