### ISSUE TITLE
PHP Fatal error

### ISSUE THREAD

**Issue by adygeez** [axis/axiscommerce#48]
```
[Wed Feb 9 16:21:57 2011] [error] PHP Fatal error: Uncaught exception 'Exception' with message 'Warning: is_readable() [<a href='function.is-readable'>function.is-readable</a>]: open_basedir restriction in effect. File(/usr/local/share/pear//home/test/www/axis/app/design/front/default/helpers/Meta.php) is not within the allowed path(s): (/home/test/) in /home/test/www/axis/library/Zend/Loader.php on line 198' in /home/test/www/axis/library/Axis/Bootstrap.php:122
```

Stack trace:
    0 [internal function]: AxisErrorHandler(2, 'is_readable() [...', '/home/test/w...', 198, Array)
    1 /home/test/www/axis/library/Zend/Loader.php(198): is_readable('/usr/local/shar...')
    2 /home/test/www/axis/library/Zend/Loader/PluginLoader.php(389): Zend_Loader::isReadable('/home/test/w...')
    3 /home/test/www/axis/library/Zend/View/Abstract.php(1174): Zend_Loader_PluginLoader->load('Meta')
    4 /home/test/www/axis/library/Zend/View/Abstract.ph in /home/test/www/axis/library/Axis/Bootstrap.php on line 122

**Comment by vovayatsyuk** [comment]
It seems that you have an error in server include paths: 
    /usr/local/share/pear//home/test/www/axis/app/design/front/default/helpers/Meta.php

Can you show us the result of the following function on your server:

```
print_r(get_include_path());
echo PATH_SEPARATOR;
```

**Comment by adygeez** [comment]
.:/usr/local/share/pear:

**Comment by vovayatsyuk** [comment]
Sorry, I wasn't correct.
Can you run this lines again but place them in install/index.php file inside AXIS_ROOT on the line 33 after set_include_path(.....):

```
print_r(get_include_path());
echo PATH_SEPARATOR;
die;
```

Thank you.

I think this workaround will help you:
Replace the code inside install/index.php
    set_include_path(
        realpath('../app/code') . PATH_SEPARATOR
        . realpath('../library') . PATH_SEPARATOR
        . get_include_path()
    );

with
    set_include_path(
        realpath('../app/code') . PATH_SEPARATOR
        . realpath('../library')/\* . PATH_SEPARATOR
        . get_include_path()*/
    );

And you need to the the same in the index.php inside AXIS_ROOT:
Replace 
    set_include_path(
        realpath('library')  . PATH_SEPARATOR
        . realpath('app/code') . PATH_SEPARATOR
        . get_include_path()
    );

with
    set_include_path(
        realpath('library')  . PATH_SEPARATOR
        . realpath('app/code')/\* . PATH_SEPARATOR
        . get_include_path()*/
    );

**Comment by adygeez** [comment]
/home/test/www/axis/library:/home/test/www/axis/app/code:.:/usr/local/share/pear:

**Comment by adygeez** [comment]
Fix with replacing helped! Now site works!
