### ISSUE TITLE
AxisAdministrator::Карта сайта - не произоводятся действия

### ISSUE THREAD

**Issue by webmayak** [axis/axiscommerce#49]
Список пустой. При нажатии на кнопки (добавить, сохранить) никаких действий не происходит
(0.7.1.1)

**Comment by 0m3r** [comment]
уже было исправлено в develop ветке 
https://github.com/axis/axiscommerce/commit/6bce500eb64a951fa8e9cb9e6423146391bef655#js/axis/admin/sitemap/sitemap.js
