### ISSUE TITLE
Failed saving metadata to metadataCache

### ISSUE THREAD

**Issue by magnezi** [axis/axiscommerce#52]
Права на запись установлены для /var
Может ли возникнуть данная прблема из-за того, что скрипт создает папки и файлы под группа/владелец apache

Fatal error: 
<pre><code>Uncaught exception 'Exception' with message 'User Notice: 
Failed saving metadata to metadataCache in /var/www/vhosts/site.com/httpdocs/library/Zend/Db/Table/Abstract.php on line 826' 
in /var/www/vhosts/site.com/httpdocs/library/Axis/Bootstrap.php:122 
</pre></code>
Stack trace: 
<pre><code>
0 /var/www/vhosts/site.com/httpdocs/library/Zend/Db/Table/Abstract.php(826): AxisErrorHandler(1024, 'Failed saving m...', '/var/www/vhosts...', 826, Array) 
1 /var/www/vhosts/site.com/httpdocs/library/Zend/Db/Table/Abstract.php(862): Zend_Db_Table_Abstract->_setupMetadata('Failed saving m...', 1024) 
2 /var/www/vhosts/site.com/httpdocs/library/Axis/Db/Table/Abstract.php(103): Zend_Db_Table_Abstract->_setupPrimaryKey() 
3 /var/www/vhosts/site.com/httpdocs/library/Zend/Db/Table/Select.php(100): Axis_Db_Table_Abstract->info() 
4 /var/www/vhosts/site.com/httpdocs/library/Zend/Db/Table/Select.php(78): Zend_Db_Table_Select->setTable() 
5 /var/www/vhosts/site.com/httpdocs/library/Axis/Db/Table/Select.php(62): Zend_Db_Table_Select->__constr in /var/www/vhosts/site.com/httpdocs/library/Axis/Bootstrap.php on line 122
</pre></code>

**Comment by 0m3r** [comment]
apache должен иметь права на запись для /var/www/vhosts/site.com/httpdocs/var

**Comment by magnezi** [comment]
Да права есть, config.php записался при установке.
Не могу понять возникшую ошибку: Failed saving metadata to metadataCache.
На локальном сервере всё работает, на хостинге нет.
P.S.
Спасибо, за вашу работу.

**Comment by 0m3r** [comment]
Да малость непонятно. На хостинге устанавливали или залили сверху 
Попробуйте в Bootstarp.php (library/Axis) закоментировать 246 строку
Zend_Db_Table_Abstract::setDefaultMetadataCache($cache); должно помочь но по правде говоря так делать плохо :)

**Comment by magnezi** [comment]
Сначала залил сайт, потом пробовал установку.
Закоментировал строку Zend_Db_Table_Abstract::setDefaultMetadataCache($cache);
Сайт работает. 
Попробую протеститировать на другом хостинге.

**Comment by 0m3r** [comment]
возможно заливали вы его не под apache а под каким нибудь ftp
собствено владелец тогда фтп а не апач. 
если есть консоль 
попробуйте 
<code>chmod -R 0777 /var/www/vhosts/site.com/httpdocs/var</code>
или как нибудь так 
<code>chown -R apache /var/www/vhosts/site.com/httpdocs/</code>

**Comment by magnezi** [comment]
Да, вы правы, заливал файлы под user ftp 
Через консоль выполнил

<p><code>chown -R apache /var/www/vhosts/site.com/httpdocs/</code></p>

Теперь сайт работает с

<p><code>Zend_Db_Table_Abstract::setDefaultMetadataCache($cache);</code></p>

Можно ли добавить в Bootstarp.php следущее:

<p><code>
chown($path, $user_name); // Set the user
</code></p>
