### ISSUE TITLE
[design control] /admin/template_mail 

### ISSUE THREAD

**Issue by azdcgo** [axis/axiscommerce#56]
I get this error when i try to access: /admin/template_mail 

script 'template/mail/index.phtml' not found in path (E:/wamp/www/app/code/Axis/Admin/views\scripts/;E:/wamp/www/app/design/admin/default/layouts/;E:/wamp/www/app/design/admin/default/templates/template/;E:/wamp/www/app/design/admin/default/templates/)<br />
    #0 E:\wamp\www\library\Zend\View\Abstract.php(876): Zend_View_Abstract->_script('template/mail/i...')<br />
    #1 E:\wamp\www\library\Zend\Controller\Action\Helper\ViewRenderer.php(897): Zend_View_Abstract->render('template/mail/i...')<br />
    #2 E:\wamp\www\library\Zend\Controller\Action\Helper\ViewRenderer.php(918): Zend_Controller_Action_Helper_ViewRenderer->renderScript('template/mail/i...', NULL)<br />
    #3 E:\wamp\www\library\Zend\Controller\Action.php(212): Zend_Controller_Action_Helper_ViewRenderer->render(NULL, NULL, false)<br />
    #4 E:\wamp\www\app\code\Axis\Admin\controllers\Template\MailController.php(52): Zend_Controller_Action->render()<br />
    #5 E:\wamp\www\library\Zend\Controller\Action.php(513): Axis_Admin_Template_MailController->indexAction()<br />
    #6 E:\wamp\www\library\Zend\Controller\Dispatcher\Standard.php(295): Zend_Controller_Action->dispatch('indexAction')<br />
    #7 E:\wamp\www\library\Zend\Controller\Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))<br />
    #8 E:\wamp\www\library\Zend\Application\Bootstrap\Bootstrap.php(97): Zend_Controller_Front->dispatch()<br />
    #9 E:\wamp\www\library\Zend\Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()<br />
    #10 E:\wamp\www\index.php(75): Zend_Application->run()<br />
    #11 {main}

**Comment by 0m3r** [comment]
fast fix 
https://github.com/axis/axiscommerce/commit/12ccbbc60e65273dcc8326dcbbd859c5a15aa165
