### ISSUE TITLE
Editable shopping cart

### ISSUE THREAD

**Issue by ghost** [axis/axiscommerce#68]
this time , edit the shopping cart ,need to manual edit the product's Quantity,then click the "update" button.

can it change the same as the "Editable shopping cart during checkout ",just click "-" or "+" can change the Quantity?

**Comment by vovayatsyuk** [comment]
You may override the shopping cart template (/app/design/front/default/templates/checkout/cart/index.phtml), and make any changes you want to.

To make the shopping cart looks like the onestep checkout cart you can grab some code from checkout page and integrate it with shopping cart page.

The one thing you will not available to do &mdash; use the ajax requests for shopping cart update (This is possible only with custom module).

http://axiscommerce.com/faq#customize-look-and-feel
