### ISSUE TITLE
about cms url

### ISSUE THREAD

**Issue by ghost** [axis/axiscommerce#74]
can we change the cms's url?
such as change  url  domain.com/page/shipping ,to domain.com/shipping ?

thanks.

**Comment by vovayatsyuk** [comment]
There are no ready to use mechanism available for this.

But you can create your module with custom routes file in etc folder:

```
$router->addRoute('cms_page_shipping', new Axis_Controller_Router_Route(
    'shipping',
    array(
        'module' => 'Axis_Cms',
        'controller' => 'view',
        'action' => 'view-page',
        'page' => 'shipping'
    )
));
```

See the routes file example in any of our modules (app/code/Axis/MODULE_NAME/etc/routes.php).
