### ISSUE TITLE
Invalid controller specified (customer_group)

### ISSUE THREAD

**Issue by ghost** [axis/axiscommerce#79]
use develop trunk, view /admin/customer_index  url  have this issue:

2011-09-01T08:27:58+06:00 DEBUG (7): Invalid controller specified (customer_group)
#0 /library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#2 /library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#3 /index.php(75): Zend_Application->run()
#4 {main}

2011-09-01T08:28:02+06:00 DEBUG (7): Invalid controller specified (customer_index)
#0 /library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#2 /library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#3 /index.php(75): Zend_Application->run()
#4 {main}

2011-09-01T08:29:55+06:00 DEBUG (7): Invalid controller specified (customer_index)
#0 /library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#1 /library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#2 /library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#3 /index.php(75): Zend_Application->run()
#4 {main}

**Comment by 0m3r** [comment]
1. get last commits: git fetch 
2. run upgrade: Axis_Account 0.2.2 on "your_host/admin/module" page

**Comment by ghost** [comment]
```
Resource id 'admin/account/wishlist' already exists in the ACL
Resource id 'admin/account/group' already exists in the ACL
Invalid controller specified (customer_group)
```

**Comment by ghost** [comment]
"your_host/admin/module" page ,show listed no module.

already clean cache. upgrade from 0.8.1

**Comment by 0m3r** [comment]
Have you enabled auto update? 'applyUpgrades' => true etc/config.php
What version of the module "Axis_Account" is installed now?

As far as I understood you have duplicated "resource_Id" in the table 'admin_acl_resource'.
Find and remove duplicated entries in 'recourse_id' column  in table 'admin_acl_resource'  (last row with 'resource_id': "admin/account/wishlist" and "admin/account/group")

> SELECT COUNT(*) FROM admin_acl_resource WHERE resource_id = "admin/account/wishlist"
> if 2 
> DELETE FROM admin_acl_resource WHERE resource_id = "admin/account/wishlist" LIMIT 1 
> 
> SELECT COUNT(*) FROM admin_acl_resource WHERE resource_id = "admin/account/group"
> if 2 
> DELETE FROM admin_acl_resource WHERE resource_id = "admin/account/group" LIMIT 1

**Comment by ghost** [comment]
ACL and view "/admin/customer_index "  issue fixed. but Invalid controller specified (customer_group) still have when view "/admin/sales_order". upgrade from 0.8.1.Axis_Account is 0.22

**Comment by 0m3r** [comment]
Do you have another?
https://github.com/axis/axiscommerce/blob/develop/js/axis/admin/sales/order/window/form/panel/orderInfo/boxCustomer.js#L32
perhaps you have cached javascript?

**Comment by ghost** [comment]
browser's cache issue.ok now. thanks.
