### ISSUE TITLE
time of load

### ISSUE THREAD

**Issue by akram786sk** [axis/axiscommerce#81]
the loading time is very slow, even taking 25-30minuts to install. clicking any link in the axis system takes nearly 2 minuts to open the page.

**Comment by vovayatsyuk** [comment]
How many products are in the database?

Please write your server configuration and value of php memory_limit option.

It would be great if you enable logging of slow queries and attach them in here.

**Comment by akram786sk** [comment]
i hav jus installed dis web app in server, i dnt create ny category nor products.

i have another issue, in admin panel whenever i move on menu, the dropdown options appear but while going on dropdown menu, it disappears

**Comment by vovayatsyuk** [comment]
What browser do you use?

**Comment by akram786sk** [comment]
google chrome
