### ISSUE TITLE
Search module XSS vulnerability

### ISSUE THREAD

**Issue by abu-umar** [axis/axiscommerce#83]
XSS can be done using the command input

Example Code: " onmouseover=prompt(XSS Code) bad="

Source: http://packetstormsecurity.org/files/view/104245/axiscommerce-xss.txt

**Comment by vovayatsyuk** [comment]
Can you reproduce it?

http://demo.axiscommerce.com/search/result?q=" onmouseover=prompt(1) bad="

**Comment by abu-umar** [comment]
Ah, sorry. Not tested it first before. I can't reproduce it. But, I'm curious about that report...

**Comment by vovayatsyuk** [comment]
This report was tested on the old version 0.7.0.4
