### ISSUE TITLE
after instalation

### ISSUE THREAD

**Issue by 3wweb** [axis/axiscommerce#85]
Helo,
I received the following screen after installation:

 • The server encountered an internal error and could not complete your request.
 • More information about this error may be available in the server error log.

**Comment by vovayatsyuk** [comment]
Hello,
You can find the error log in the AXIS_ROOT/var/logs/php.log file.

Or you can change the environment to development and see all errors directly on the page:
open AXIS_ROOT/.htaccess file and change the first line from

```
SetEnv APPLICATION_ENV production
```

to

```
SetEnv APPLICATION_ENV development
```

**Comment by 3wweb** [comment]
thanks,
 I will try and get in touch.

**Comment by 3wweb** [comment]
Hi,
2011-09-22T17:04:10-03:00 DEBUG (7): script 'index/index.phtml' not found in path (/home/3wweb/www/axis/app/design/front/default/layouts/:/home/3wweb/www/axis/app/design/front/default/templates/core/:/home/3wweb/www/axis/app/design/front/default/templates/)
#0 /home/3wweb/www/axis/library/Zend/View/Abstract.php(884): Zend_View_Abstract->_script('index/index.pht...')
#1 /home/3wweb/www/axis/library/Zend/Controller/Action/Helper/ViewRenderer.php(897): Zend_View_Abstract->render('index/index.pht...')
#2 /home/3wweb/www/axis/library/Zend/Controller/Action/Helper/ViewRenderer.php(918): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index/index.pht...', NULL)
#3 /home/3wweb/www/axis/library/Zend/Controller/Action.php(212): Zend_Controller_Action_Helper_ViewRenderer->render(NULL, NULL, false)
#4 /home/3wweb/www/axis/app/code/Axis/Core/controllers/IndexController.php(43): Zend_Controller_Action->render()
#5 /home/3wweb/www/axis/library/Zend/Controller/Action.php(513): IndexController->indexAction()
#6 /home/3wweb/www/axis/library/Zend/Controller/Dispatcher/Standard.php(295): Zend_Controller_Action->dispatch('indexAction')
#7 /home/3wweb/www/axis/library/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#8 /home/3wweb/www/axis/library/Zend/Application/Bootstrap/Bootstrap.php(97): Zend_Controller_Front->dispatch()
#9 /home/3wweb/www/axis/library/Zend/Application.php(366): Zend_Application_Bootstrap_Bootstrap->run()
#10 /home/3wweb/www/axis/index.php(75): Zend_Application->run()
#11 {main}

**Comment by vovayatsyuk** [comment]
Looks like everything is correct. 

Can you look at the app/design/front/default/templates/core/index folder? Do you have a file index.phtml inside it?

Try to navigate to the contacts page: example.com/contacts. Does it work?

**Comment by 3wweb** [comment]
folder in the folder there is no core index.
 I tested the contacts folder and opened out.

 carefully.

**Comment by 3wweb** [comment]
core does not exist within the folder index.
 I tested the contacts folder and opened out.

 carefully.

**Comment by 3wweb** [comment]
I found the folder on my computer, I can not explain why the ftp did not, but thanks for your attention.
 Very quickly your answer.

 Thank you.

**Comment by vovayatsyuk** [comment]
Does it works now?

I'm glad that I could help you.
