### ISSUE TITLE
Value set error

### ISSUE THREAD

**Issue by hrvojebabiczg** [axis/axiscommerce#86]
Warning: Invalid argument supplied for foreach() in /home/vrijemem/public_html/app/code/Axis/Admin/controllers/Catalog/ProductOptionValuesetController.php on line 146

**Comment by hrvojebabiczg** [comment]
Warning: array_filter() [function.array-filter]: The first argument should be an array in /home/vrijemem/public_html/app/code/Axis/Admin/controllers/Cms/IndexController.php on line 268

**Comment by vovayatsyuk** [comment]
Looks like you have magic_quotes enabled. To use Axis you should turn them off.

See the related topics: 
http://axiscommerce.com/forum/nvalid-argument-supplied
http://axiscommerce.com/forum/php-magic-quotes
