### ISSUE TITLE
Всплывающее меню админки

### ISSUE THREAD

**Issue by evgeniybilyk** [axis/axiscommerce#87]
Доброго времени суток!
Спасибо Вам за хороший продукт!
Только установил, и вот не могу понять как работает всплывающее меню админки, либо это глюк у меня), либо у браузера), хотя пробовал и в трех разных: хром, опера, мозила
Значит ситуация такая.Всплывающее меню в админке срабатывает через раз, ито я не могу отловить закономерность, т.е. если подвести мишкой к главному меню, то список подменю раскрывается, но оно неактивное, т.е. если сразу мишку опускать вниз, то список подменю сразу скрывается, но иногда срабатывает и нормально.

что это может быть?

**Comment by vovayatsyuk** [comment]
Проблема уже была исправлена. Замените файл skin/admin/default/css/navigation.css этим https://raw.github.com/axis/axiscommerce/e6619133bfd87b8aaa0c40c418cef292cc6f1cfb/skin/admin/default/css/navigation.css

**Comment by evgeniybilyk** [comment]
Спасибо, работает отлично ...
