### ISSUE TITLE
Неправильное отображение флагов языка в карточке товара

### ISSUE THREAD

**Issue by brokerUA** [axis/axiscommerce#9]
На странице _admin/locale_language_ установлена одна локаль ru_RU, в админке снизу (выпадающий список Interface locale) указано два перевода English (United States) (en_US) и українська (Україна) (uk_UA).
При редактировании карточки товара в зависимости от установленного языка перевода показывается флаг США или Украины, но при нажатии на него в выпадающем списке только флаг РФ.
Как я понимаю в карточке товара вообще не должны были отображаться флаги США и Украины, т.к. существует только локаль РФ.

P.S. при первом заходе в админку, каталог товаров (_admin/catalog_index_) не загружается, приходиться переключить лакализацию админки на другой язык, после чего каталог появляется. <a href="http://s60.radikal.ru/i169/1010/df/04ad86539aed.jpg">Скрин ошибок в firebug</a>.

**Comment by vovayatsyuk** [comment]
Исправлено.
Также убрана логика смены языка данных при изменении языка интерфейса.
Язык меняется только из конфигурации locale/main/language_admin.

**Comment by brokerUA** [comment]
Актуальный вопрос: 
при первом заходе в админку, каталог товаров (_admin/catalog_index_) не загружается, приходиться переключить лакализацию админки на другой язык, после чего каталог появляется. <a href="http://s60.radikal.ru/i169/1010/df/04ad86539aed.jpg">Скрин ошибок в firebug</a>.

**Comment by 0m3r** [comment]
сколько и каких локалей(языков) у вас определено для фронтенда(тех в которых вводится продукт)
какие у Вас значения конфиг опций locale/main/language_admin, locale/main/locale

**Comment by brokerUA** [comment]
На странице admin/locale_language установлена одна локаль ru_RU

locale/main/language_front = русский
locale/main/language_admin = русский
locale/main/locale = росiйська (Росiя)

в папке app\locale\ лежит две не измененные папки en_US и uk_UA

**Comment by 0m3r** [comment]
временное решение 
Axis_Controller_Action line  205  
Axis::session()->locale : 'auto';//Axis_Locale::getDefaultLocale();

**Comment by brokerUA** [comment]
Спасибо, подскажите в каком файле менять?
Нашел в
\library\Axis\Bootstrap.php
\library\Axis\Controller\Action.php

**Comment by 0m3r** [comment]
2

**Comment by vovayatsyuk** [comment]
Исправлено https://github.com/axis/axiscommerce/commit/00d2417c5cf8830d811e29477b740bdb85c5e858
