### ISSUE TITLE
Exception when adding new product

### ISSUE THREAD

**Issue by benyaminshoham** [axis/axiscommerce#91]
If there is no category selected. Other errors give some detail and navigate to the right tab in the "add product" dialog, but this one just throws a bunch of exception text.

**Comment by vovayatsyuk** [comment]
Please, post here the text of exception you received.

**Comment by benyaminshoham** [comment]
This doesn't happen anymore, and I don't have the exception text. Maybe it
happens only on the first product on a clean system?

**Comment by vovayatsyuk** [comment]
I can't reproduce this bug. Even on the empty catalog everything works fine.
