### ISSUE TITLE
PDO::MYSQL_ATTR_INIT_COMMAND commented out

### ISSUE THREAD

**Issue by akger1379** [axis/axiscommerce#96]
library/Axis/Bootstrap.php [line 227]

Why you commented out that line? I wouldn't use the integer value as this could change somewhen...

**Comment by akger1379** [comment]
You may use the "charset" config parameter instead of "driver_options" and it should run fine:

``` php
$db = Zend_Db::factory('Pdo_Mysql', array(
            'host'           => $config->db->host,
            'username'       => $config->db->username,
            'password'       => $config->db->password,
            'dbname'         => $config->db->dbname,
            'charset         => 'UTF8'
            ) ...
```

**Comment by vovayatsyuk** [comment]
Thank you. It was commented because of problems in some version of php 5.3.

I've applied your patch. Will push it to the repository later.
